# 데이터셋 로드

In [2]:
import pandas as pd
import numpy as np
import chardet

# encoding 설정
with open('fire_firefighting.csv', 'rb') as file:
    result = chardet.detect(file.read())
    encoding = result['encoding']

In [3]:
# 화재 데이터
fire_fighting_df = pd.read_csv('fire_firefighting.csv', encoding=encoding)
fire_fighting_df

,Unnamed: 0,fire_firefighting.num,fire_firefighting.year,fire_firefighting.tm,fire_firefighting.district_1,fire_firefighting.district_2,fire_firefighting.fire_type_1,fire_firefighting.fire_type_2,fire_firefighting.ignition_factor_category_1,fire_firefighting.ignition_factor_category_2,fire_firefighting.casualties,fire_firefighting.dead,fire_firefighting.injury,fire_firefighting.property_damage,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
0,1,1,2018,2018-01-01 00:03:00,경기도,고양시일산동구,건축,구조물,전기적 요인,미확인단락,1,0,1,24099,주거,단독주택,상가주택(주택부분에서 화재가 발생한 경우에만 해당)
1,2,2,2018,2018-01-01 00:12:00,전북특별자치도,완주군,건축,구조물,부주의,가연물 근접방치,0,0,0,2758,주거,단독주택,단독주택
2,3,3,2018,2018-01-01 00:16:00,경기도,남양주시,임야,NaN,부주의,담배꽁초,0,0,0,28,임야,산불,공유림
3,4,4,2018,2018-01-01 00:28:00,충청남도,보령시,건축,구조물,기계적 요인,과열/ 과부하,0,0,0,1942,주거,단독주택,단독주택
4,5,5,2018,2018-01-01 00:38:00,전라남도,순천시,건축,구조물,부주의,가연물 근접방치,0,0,0,1401,주거,단독주택,단독주택
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236332,236333,38853,2023,2023-12-31 23:00:00,경상남도,양산시,건축,구조물,제품결함,제조상결함,0,0,0,99,판매/업무시설,일반업무,오피스텔
236333,236334,38854,2023,2023-12-31 23:05:00,부산광역시,북구,건축,구조물,부주의,담배꽁초,0,0,0,30,주거,단독주택,단독주택
236334,236335,38855,2023,2023-12-31 23:35:00,충청북도,영동군,건축,구조물,미상,미상,0,0,0,13495,주거,기타주택,기타 주택
236335,236336,38856,2023,2023-12-31 23:48:00,서울특별시,성북구,건축,구조물,부주의,음식물 조리중,0,0,0,12,주거,공동주택,연립주택
236336,236337,38857,2023,2023-12-31 23:50:00,경기도,김포시,건축,구조물,전기적 요인,절연열화에 의한 단락,0,0,0,3509,산업시설,공장시설,금속기계 및 기구공업

In [3]:
# 날씨 데이터
weather_df = pd.read_csv('fire_weather.csv', encoding=encoding)
weather_df

,Unnamed: 0,fire_weather.tm,fire_weather.district_1,fire_weather.district_2,fire_weather.stn,fire_weather.ta_max,fire_weather.ta_min,fire_weather.ta_max_min,fire_weather.rn_day,fire_weather.ws_max,fire_weather.ws_ins_max,fire_weather.ws_mean,fire_weather.ws_min,fire_weather.hm_max,fire_weather.hm_mean,fire_weather.hm_min
0,1,2018-01-01,서울특별시,종로구,108,3.8,-5.1,8.9,0.0,3.8,7.0,1.5,0.5,55.6,39.3,20.4
1,2,2018-01-02,서울특별시,종로구,108,1.8,-4.3,6.1,0.0,4.9,8.5,1.8,0.2,70.6,43.6,20.1
2,3,2018-01-03,서울특별시,종로구,108,-0.4,-7.1,6.7,0.0,3.5,6.6,2.1,0.8,54.0,41.1,29.3
3,4,2018-01-04,서울특별시,종로구,108,-0.7,-8.7,8.0,0.0,3.5,5.8,1.4,0.5,56.7,44.1,31.3
4,5,2018-01-05,서울특별시,종로구,108,1.6,-5.6,7.2,0.0,3.6,8.0,1.7,0.6,56.0,48.5,33.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552574,552575,2023-12-27,강원특별자치도,양양군,670,6.6,-3.0,9.6,0.0,4.1,5.5,2.2,0.7,83.6,61.7,48.1
552575,552576,2023-12-28,강원특별자치도,양양군,670,7.4,-3.8,11.2,0.0,6.5,10.1,3.0,0.2,89.0,54.1,24.5
552576,552577,2023-12-29,강원특별자치도,양양군,670,9.3,1.6,7.7,0.0,7.2,10.2,4.1,1.9,54.5,44.2,29.8
552577,552578,2023-12-30,강원특별자치도,양양군,670,6.0,1.4,4.6,0.5,5.8,9.0,1.9,0.3,94.4,68.9,46.0
552578,552579,2023-12-31,강원특별자치도,양양군,670,3.0,0.6,2.4,11.0,5.2,7.9,2.0,0.2,95.9,91.9,85.6

In [4]:
# 특보 데이터
weather_special_df = pd.read_csv('fire_weather_special.csv', encoding=encoding)
weather_special_df

,Unnamed: 0,fire_weather_special.tm,fire_weather_special.district_1,fire_weather_special.district_2,fire_weather_special.stn,fire_weather_special.reg_id,fire_weather_special.wrn,fire_weather_special.lvl,fire_weather_special.cmd
0,1,2018-01-01 4:00,경상북도,울릉군,115,L1072100,W,2,3
1,2,2018-01-01 10:00,경상북도,포항시남구,138,L1072400,D,2,1
2,3,2018-01-01 10:00,경상북도,포항시북구,138,L1072400,D,2,1
3,4,2018-01-01 10:00,부산광역시,중구,159,L1080100,D,2,1
4,5,2018-01-01 10:00,부산광역시,서구,159,L1080100,D,2,1
...,...,...,...,...,...,...,...,...,...
235486,235487,2023-12-31 22:00,인천광역시,중구,112,L1014100,W,2,3
235487,235488,2023-12-31 22:00,인천광역시,동구,112,L1014100,W,2,3
235488,235489,2023-12-31 22:00,인천광역시,미추홀구,112,L1014100,W,2,3
235489,235490,2023-12-31 22:00,인천광역시,옹진군,112,L1014100,W,2,3
235490,235491,2023-12-31 22:00,대구광역시,동구,143,L1075020,W,2,3

In [5]:
ysg_df = pd.read_csv('fire_weather_special_sample_유성구태풍.csv', encoding=encoding)
ysg_df

,Unnamed: 0,fire_weather_special.tm,fire_weather_special.district_1,fire_weather_special.district_2,fire_weather_special.stn,fire_weather_special.reg_id,fire_weather_special.wrn,fire_weather_special.lvl,fire_weather_special.cmd
0,14044,2018-08-23 11:58:00,대전광역시,유성구,133,L1030100,T,1,1
1,14748,2018-08-23 13:00:00,대전광역시,유성구,133,L1030100,T,2,1
2,14916,2018-08-24 03:00:00,대전광역시,유성구,133,L1030100,T,3,2
3,15090,2018-08-24 07:30:00,대전광역시,유성구,133,L1030100,T,2,2
4,15216,2018-08-24 10:00:00,대전광역시,유성구,133,L1030100,T,2,3
5,17481,2018-10-06 11:58:00,대전광역시,유성구,133,L1030100,T,1,1
6,17986,2018-10-06 05:50:00,대전광역시,유성구,133,L1030100,T,2,1
7,18144,2018-10-06 15:00:00,대전광역시,유성구,133,L1030100,T,2,3
8,35794,2019-09-07 05:59:00,대전광역시,유성구,133,L1030100,T,1,1
9,36128,2019-09-07 04:00:00,대전광역시,유성구,133,L1030100,T,3,1
10,36528,2019-09-07 16:00:00,대전광역시,유성구,133,L1030100,T,3,4
11,37622,2019-09-22 17:58:00,대전광역시,유성구,133,L1030100,T,1,1
12,38269,2019-09-22 15:00:00,대전광역시,유성구,133,L1030100,T,2,1
13,38424,2019-09-22 22:20:00,대전광역시,유성구,133,L1030100,T,2,3
14,38927,2019-10-03 05:59:00,대전광역시,유성구,133,L1030100,T,1,1
15,39343,2019-10-02 20:00:00,대전광역시,유성구,133,L1030100,T,2,1
16,39530,2019-10-03 03:00:00,대전광역시,유성구,133,L1030100,T,2,3
17,58032,2020-08-26 17:58:00,대전광역시,유성구,133,L1030100,T,1,1
18,58447,2020-08-26 19:00:00,대전광역시,유성구,133,L1030100,T,2,1
19,58654,2020-08-27 06:00:00,대전광역시,유성구,133,L1030100,T,2,3
20,59542,2020-09-02 23:58:00,대전광역시,유성구,133,L1030100,T,1,1
21,59954,2020-09-02 17:00:00,대전광역시,유성구,133,L1030100,T,2,1
22,60242,2020-09-03 02:00:00,대전광역시,유성구,133,L1030100,T,3,2
23,60309,2020-09-03 09:00:00,대전광역시,유성구,133,L1030100,T,3,3
24,60781,2020-09-07 08:59:00,대전광역시,유성구,133,L1030100,T,1,1
25,61154,2020-09-07 05:00:00,대전광역시,유성구,133,L1030100,T,2,1
26,61370,2020-09-07 17:00:00,대전광역시,유성구,133,L1030100,T,2,3
27,97373,2022-09-05 23:58:00,대전광역시,유성구,133,L1030100,T,1,1
28,97675,2022-09-05 21:00:00,대전광역시,유성구,133,L1030100,T,2,1
29,97819,2022-09-06 00:00:00,대전광역시,유성구,133,L1030100,T,3,2
30,97933,2022-09-06 07:30:00,대전광역시,유성구,133,L1030100,T,2,2
31,98070,2022-09-06 09:20:00,대전광역시,유성구,133,L1030100,T,2,3
32,117327,2023-08-10 05:58:00,대전광역시,유성구,133,L1030100,T,1,1
33,118136,2023-08-10 01:00:00,대전광역시,유성구,133,L1030100,T,2,1
34,118277,2023-08-10 09:00:00,대전광역시,유성구,133,L1030100,T,3,2
35,118391,2023-08-10 16:30:00,대전광역시,유성구,133,L1030100,T,2,2
36,118533,2023-08-10 22:00:00,대전광역시,유성구,133,L1030100,T,2,3
37,135950,2018-08-24 07:30:00,대전광역시,유성구,133,S1251300,T,2,4
38,135954,2018-08-24 07:30:00,대전광역시,유성구,133,S1251400,T,3,4
39,150646,2019-09-07 19:00:00,대전광역시,유성구,133,L1031600,T,3,4
40,152727,2019-10-03 03:00:00,대전광역시,유성구,133,S1251400,T,2,4
41,168471,2020-08-27 06:00:00,대전광역시,유성구,133,S1251400,T,3,4
42,168615,2020-08-27 09:00:00,대전광역시,유성구,133,S1251300,T,3,4
43,169832,2020-09-03 09:00:00,대전광역시,유성구,133,S1251300,T,3,4
44,169836,2020-09-03 09:00:00,대전광역시,유성구,133,S1251400,T,3,4
45,171017,2020-09-07 17:00:00,대전광역시,유성구,133,S1251300,T,2,4
46,171019,2020-09-07 17:00:00,대전광역시,유성구,133,S1251400,T,2,4
47,171023,2020-09-07 17:00:00,대전광역시,유성구,133,L1031600,T,3,4
48,207142,2022-09-06 07:30:00,대전광역시,유성구,133,L1031600,T,2,4
49,207242,2022-09-06 09:20:00,대전광역시,유성구,133,S1251400,T,2,4
50,227421,2023-08-10 22:00:00,대전광역시,유성구,133,S1251400,T,2,4
51,227439,2023-08-10 22:00:00,대전광역시,유성구,133,L1031600,T,2,4
52,227587,2023-08-11 06:00:00,대전광역시,유성구,133,S1251300,T,2,4

# 기본 eda
: 지역 (지형적 특성, 기후적 특성, 지역적 특성), 월, 장소 => 화재유형, 발화요인 => 사상자 수, 재산피해액
1. fire_fighting_df
    - 도별 화재 발생 횟수
    - 도별 화

## 1. fire_fighting

In [6]:
fire_fighting_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 236337 entries, 0 to 236336
Data columns (total 17 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   Unnamed: 0                                    236337 non-null  int64
 1   fire_firefighting.num                         236337 non-null  int64
 2   fire_firefighting.year                        236337 non-null  int64
 3   fire_firefighting.tm                          236337 non-null  object
 4   fire_firefighting.district_1                  236337 non-null  object
 5   fire_firefighting.district_2                  236337 non-null  object
 6   fire_firefighting.fire_type_1                 236337 non-null  object
 7   fire_firefighting.fire_type_2                 182619 non-null  object
 8   fire_firefighting.ignition_factor_category_1  236337 non-null  object
 9   fire_firefighting.ignition_factor_category_2  236337 non-null  object
 10  fire_firefighting.casualties                  236337 non-null  int64
 11  fire_firefighting.dead                        236337 non-null  int64
 12  fire_firefighting.injury                      236337 non-null  int64
 13  fire_firefighting.property_damage             236337 non-null  int64
 14  fire_firefighting.location_category_1         236337 non-null  object
 15  fire_firefighting.location_category_2         236337 non-null  object
 16  fire_firefighting.location_category_3         236337 non-null  object
dtypes: int64(7), object(10)
memory usage: 30.7+ MB

In [7]:
print('===== fire type 1 =====')
print(fire_fighting_df['fire_firefighting.fire_type_1'].unique())
print()
print('===== fire type 2 =====')
print(fire_fighting_df['fire_firefighting.fire_type_2'].unique())
print()
print('===== ignition factor category 1 =====')
print(fire_fighting_df['fire_firefighting.ignition_factor_category_1'].unique())
print()
print('===== ignition factor category 2 =====')
print(fire_fighting_df['fire_firefighting.ignition_factor_category_2'].unique())
print()
print('===== location category 1 =====')
print(fire_fighting_df['fire_firefighting.location_category_1'].unique())
print()
print('===== location category 2 =====')
print(fire_fighting_df['fire_firefighting.location_category_2'].unique())
print()
print('===== location category 3 =====')
print(fire_fighting_df['fire_firefighting.location_category_3'].unique())
print()

===== fire type 1 =====
['건축' '임야' '기타(쓰레기 화재등)' '자동차' '위험물' '선박']

===== fire type 2 =====
['구조물' nan '철도차량' '가스제조소등' '항공기']

===== ignition factor category 1 =====
['전기적 요인' '부주의' '기계적 요인' '미상' '방화의심' '기타' '방화' '교통사고' '가스누출(폭발)' '화학적 요인'
 '자연적인 요인' '제품결함']

===== ignition factor category 2 =====
['미확인단락' '가연물 근접방치' '담배꽁초' '과열/ 과부하' '음식물 조리중' '불씨/불꽃/화원방치' '접촉불량에 의한 단락'
 '절연열화에 의한 단락' '미상' '쓰레기 소각' '방화의심' '역화' '기타(기계적요인)' '기타' '과부하/과전류' '방화'
 '누전/지락' '기타(부주의)' '용접/ 절단/ 연마' '트래킹에 의한 단락' '압착/손상에 의한 단락' '노후' '정비불량'
 '빨래삶기' '오일/연료누설' '폭죽놀이' '교통사고' '논/임야태우기' '기타(전기적요인)' '반단선' '불장난'
 '가스누출(폭발)' '자동제어 실패' '유류 취급중' '화학적 폭발' '자연발화' '기타(화학적요인)' '층간단락'
 '화학적 발화(유증기 확산)' '기타(자연적인요인)' '혼촉발화' '수동제어 실패' '금수성물질의 물과 접촉' '자연적 재해'
 '돋보기 효과' '기기(전기/ 기계 등) 사용.설치부주의' '설계상결함' '기타(제품결함)' '제조상결함']

===== location category 1 =====
['주거' '임야' '기타' '생활서비스' '기타서비스' '산업시설' '판매/업무시설' '자동차/철도차량' '운수자동차시설'
 '교육시설' '집합시설' '위험물/가스제조소' '의료/복지시설' '선박/항공기' '문화재시설']

===== location category 2 =====
['단독주택' '산불' '공동주택' '야외' '음식점' '일상서비스' '기타건축물' '동식물시설' '위생시설' '숙박시설'
 '기타주택' '창고시설' '들불' '자동차' '판매시설' '일반업무' '건설기계' '농업기계' '작업장' '공장시설' '자동차시설'
 '연구/학원' '종교시설' '군사시설' '위험물제조소등' '학교' '오락시설' '도로' '공연장' '발전시설' '건강시설'
 '공공기관' '운동시설' '노유자시설' '의료시설' '위락시설' '선박' '역사/터미널' '관람장' '전시장' '문화재'
 '청소년시설' '가스제조소등' '항공시설' '군용차량' '철도차량' '항만시설' '지중시설' '교정시설' '항공기']

===== location category 3 =====
['상가주택(주택부분에서 화재가 발생한 경우에만 해당)' '단독주택' '공유림' '다세대주택' '기타야외' '일반주점' '의류'
 '아파트' '쓰레기' '사유림' '기타 건축물' '기타 동식물시설' '횟집' '양수장/ 정수장' '여관' '컨테이너(주거용)'
 '창고/ 물품저장소' '들판' '승용자동차' '상점가' '커피숍/다방/카페(휴게)' '버스' '한식' '다가구주택' '오피스텔'
 '모텔' '기타 건설기계' '기타 주택' '경운기' '기타 작업장' '치킨/족발' '그 밖의 공업' '농예용 온실' '다중주택'
 '기타 들불' '제과점/빵집/떡집(휴게)' '자동차검사장/ 매매장/ 부속상/ 정비공장' '일반상점' '일반학원' '교육원'
 '기타 창고' '세탁소' '공터' '기타 공동주택' '기타 일상서비스' '기숙사' '화물자동차' '시장' '고시원(원룸텔)'
 '기타 판매시설' '덤프트럭' '사찰' '일반회사' '인쇄업' '기타 군사시설' '볏짚' '우사' '야적장' '기타 위험물제조소'
 '일반빌딩' '식료품공업' '상가빌딩' '기타 승합자동차' '고등학교' '분식' '굴삭기' '버섯재배사' '연립주택' '호프집'
 '기타 단독주택' '노래연습장' '가로등' '대학교' '중식' '비닐하우스' '극장' '발전소(수력/ 화력)' '폐기물재활용시설'
 '금속기계 및 기구공업' '전통시장' '숲' '제재 및 목공업' '치킨/족발(휴게)' '고철처리소/ 고물상' '철물점'
 '전기/ 전자공업' '교회' '화학공업' '기타도로' '국유림' '기타 건강시설' '논밭두렁' '돈사' '펄프 및 제지공업'
 '특수자동차' '커피숍/다방/카페' '농장' '일식' '간이음식점' '방직공업' '폐기물처리시설' '공중화장실'
 '기타 일반업무시설' '소형 승합차' '냉장/ 냉동창고' '노상매점' '분식(휴게)' '문방구' '수리/A/S/상하수도'
 'PC방(인터넷게임제공업)' '이미용실' '펜션' '국가 및 지방자치단체 청사' '기타 연구/학원' '기타 숙박시설'
 '주상복합아파트' '계사' '기타 공연장' '할인점(마트)' '기타 운동시설' '아동복지시설' '쇼핑센터' '기타 음식점' '양식'
 '당구장' '외국어학원' '기타 오락시설' '종합병원' '캠핑용 자동차/트레일러' '유흥주점' '기도원' '목장' '병원'
 '기타 자동차시설' '공업사' '목욕장(사우나/ 찜질방)' '카센터' '단란주점' '기타 공공기관' '특수학교' '바지선'
 '지하상가' '패스트푸드' '기타 발전시설' '인쇄소' '철도역사' '어선' '요양시설' '기타 위생시설' '횟집(휴게)'
 '골프장' '요양소' '양식(휴게)' '부동산 중개업소' '기타 선박' '변압기' '유치원' '민박' '세차장/ 폐차장'
 '석유공업' '산장' '의원' '꽃집(화원)' '금융기관(농협 등)' '전봇대' '중학교' '체력단련장(헬스장)' '기타 농업기계'
 '테니스장/ 정구장' '공사' '오토바이' '콘도미니엄' '호텔' '초등학교' '화장품' '광업' '모닥불' '독서실' '과수원'
 '골프연습장' '주유취급소' '목공소/ 건재상' '노인복지시설' '묘지' '여인숙' '기타 종교시설' '패스트푸드(휴게)'
 '한의원' '예체능학원' '주차장' '한식(휴게)' '연구소' '기타 의료시설' '어린이집' '철공소' '편의점'
 '요업 및 토석공업' '치과병원' '유람선' '예식장' '수영장' '중식(휴게)' '승마장' '경로당' '볼링장' '정신병원'
 '사진관' '기타 위락시설' '체육관' '트랙터' '성당' '기타 관람장' '정미소' '백화점' '관망탑' '모델하우스'
 '실내야구장' '제조소' '마사지(안마/ 지압 등)' '분뇨시설' '게임제공업' '자동차운전학원/ 자동차정비학원' '수족관'
 '목초지' '제과점' '관리사무소' '포장마차' '에어로빅장' '하역장' '동물병원' '장례식장' '스크린골프연습장' '운동장'
 '기타 전시장' '약국' '공원' '공중전화박스' '국가지정문화재' '휴게텔(수면방)' 'Convention Center'
 '생활권수련시설(청소년수련관/ 청소년문화의집 등)' '화물터미널' '기타 역사/터미널' '기타휴게음식점' '기타 학교' '공관'
 '박물관' '군.경사격장' '시계/안경/금속점' '산후조리원' '기타 가스제조소' '기타 항공시설' '시도지정문화재' '탁구장'
 '수도원' '기원' '옥외탱크저장소' '콜라텍' '사회복지시설' '간이음식점(휴게)' '화물선' '경기장' '직업훈련소'
 '지하철역사' '유조선' '기계장치의 주차시설' '기념관' '음악당' '마을회관' '여객자동차터미널' '멀티미디어콘텐츠'
 '장애인재활시설' '변전소' '연극장' '지하탱크저장소' '군용차량' '판매취급소' '기타 문화재' '전동차' '도축장' '서점'
 '도서관' '옥내저장소' '사당' '미술관' '송/ 배전설비' '수녀원' '도계장' '산업전시장' '투전기업소 및 카지노업소'
 '조선소' '일반취급소' '연회장' '신문사' '기관차' '휴게소' '터널' '기타 노유자시설' '복합영상물제공업'
 '무도장 및 무도학원' '수상레저기구(보트등)' '특수작업선(해양관측선등)' '기타 청소년시설' '일식(휴게)' '교도소/ 구치소'
 '고압가스저장시설' '여객선' '기타 항만시설' '가스공급시설' '롤러스케이트장' '복합유통제공업' '온천장' '기타 지중시설'
 '기타 교정시설' '원자력발전소' '종합학원' '화장장' '이동탱크저장소' '비디오대여점' '체육도장(태권도/ 검도 등)'
 '근로복지시설' '기타 군용차량' '한방병원' '자연권수련시설(청소년수련원/ 청소년야영장 등)' '공동구' '막사' '옥외저장소'
 '외항선' '정부미도정공장' '여행객이용시설(공항)' '단식수련원/ 기수련원' '요가수련장' '레코드점' '고압가스제조시설'
 '박람회장' '비행기' '양로원' '종묘배양시설' '액화석유가스저장시설' '귀/손톱등 케어방' '숙박공유업' '태양광발전'
 '요양병원' '기타(철도차량)' '스케이트장' '태양열발전' '조력발전' '과학관' '외교공관 및 사택' '풍력발전'
 '연료전지발전설비' '여객이용시설' '옥내탱크저장소' '경마장' '경비행기' '함정(군함등)' '통신시설(관제소/ 송신소 등)'
 '기타 항공기' '키스방' '실내낚시터' '이착륙시설(활주로/ 유도등 등)' '실내사격장' '비디오감상실/ 비디오소극장'
 '회전익항공기(헬리콥터)' '전력구/ 통신구' '납골당' '이송취급소']

In [8]:
import sys
sys.path.append(r'/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages')
import pygwalker as pyg

walker = pyg.walk(fire_fighting_df)

Box(children=(HTML(value='<div id="ifr-pyg-00061837c7a77ae19nK6kV1Eb27xvjfR" style="height: auto">\n    <head>…

In [9]:
fire_fighting_df.columns

Index(['Unnamed: 0', 'fire_firefighting.num', 'fire_firefighting.year',
       'fire_firefighting.tm', 'fire_firefighting.district_1',
       'fire_firefighting.district_2', 'fire_firefighting.fire_type_1',
       'fire_firefighting.fire_type_2',
       'fire_firefighting.ignition_factor_category_1',
       'fire_firefighting.ignition_factor_category_2',
       'fire_firefighting.casualties', 'fire_firefighting.dead',
       'fire_firefighting.injury', 'fire_firefighting.property_damage',
       'fire_firefighting.location_category_1',
       'fire_firefighting.location_category_2',
       'fire_firefighting.location_category_3'],
      dtype='object')

In [10]:
fire_fighting_df.describe()

,Unnamed: 0,fire_firefighting.num,fire_firefighting.year,fire_firefighting.casualties,fire_firefighting.dead,fire_firefighting.injury,fire_firefighting.property_damage
count,236337.000000,236337.000000,236337.000000,236337.000000,236337.000000,236337.000000,2.363370e+05
mean,118169.000000,19738.183141,2020.458180,0.062115,0.008128,0.053986,2.232522e+04
std,68224.759622,11444.549633,1.728707,0.622223,0.153814,0.540785,1.195884e+06
min,1.000000,1.000000,2018.000000,0.000000,0.000000,0.000000,0.000000e+00
25%,59085.000000,9848.000000,2019.000000,0.000000,0.000000,0.000000,9.900000e+01
50%,118169.000000,19695.000000,2020.000000,0.000000,0.000000,0.000000,5.500000e+02
75%,177253.000000,29543.000000,2022.000000,0.000000,0.000000,0.000000,3.314000e+03
max,236337.000000,42338.000000,2023.000000,190.000000,39.000000,151.000000,4.743233e+08

In [11]:
column_list = fire_fighting_df.columns.to_list()
for i in range(len(column_list)):
    key = column_list[i]
    print(f'===== {key} =====')
    print(fire_fighting_df[key].unique())
    print()

===== Unnamed: 0 =====
[     1      2      3 ... 236335 236336 236337]

===== fire_firefighting.num =====
[    1     2     3 ... 42336 42337 42338]

===== fire_firefighting.year =====
[2018 2019 2020 2021 2022 2023]

===== fire_firefighting.tm =====
['2018-01-01 00:03:00' '2018-01-01 00:12:00' '2018-01-01 00:16:00' ...
 '2023-12-31 23:35:00' '2023-12-31 23:48:00' '2023-12-31 23:50:00']

===== fire_firefighting.district_1 =====
['경기도' '전북특별자치도' '충청남도' '전라남도' '서울특별시' '경상남도' '울산광역시' '부산광역시' '강원특별자치도'
 '충청북도' '대구광역시' '제주특별자치도' '대전광역시' '경상북도' '광주광역시' '인천광역시' '세종특별자치시']

===== fire_firefighting.district_2 =====
['고양시일산동구' '완주군' '남양주시' '보령시' '순천시' '강북구' '밀양시' '안성시' '창원시성산구' '김해시' '장흥군'
 '관악구' '울주군' '사하구' '정선군' '남구' '영동군' '동구' '예산군' '제주시' '수원시장안구' '거제시' '북구'
 '김포시' '강릉시' '의왕시' '합천군' '금천구' '원주시' '평택시' '부산진구' '대덕구' '의령군' '광명시' '인제군'
 '포항시북구' '영등포구' '전주시완산구' '성동구' '해남군' '송파구' '중구' '서구' '청주시청원구' '양주시'
 '성남시분당구' '화성시' '경주시' '당진시' '상주시' '철원군' '괴산군' '서산시' '강동구' '구미시' '파주시'
 '동작구' '단양군' '안양시동안구' '구리시' '양양군' '안양시만안구' '강화군' '강남구' '군산시' '중랑구' '연수구'
 '광진구' '부여군' '영주시' '청주시흥덕구' '기장군' '도봉구' '수원시팔달구' '강진군' '경산시' '수영구' '진주시'
 '정읍시' '목포시' '동대문구' '천안시동남구' '아산시' '충주시' '고령군' '남해군' '창원시마산회원구' '동해시'
 '함안군' '용인시처인구' '서천군' '서귀포시' '공주시' '문경시' '청주시상당구' '고성군' '고양시덕양구' '천안시서북구'
 '남원시' '달서구' '의정부시' '포천시' '성주군' '남동구' '사천시' '순창군' '구로구' '은평구' '동두천시'
 '성남시중원구' '광산구' '칠곡군' '성남시수정구' '양산시' '종로구' '창원시의창구' '금산군' '논산시' '유성구'
 '강서구' '양천구' '김천시' '시흥시' '태안군' '옹진군' '서초구' '마포구' '부천시' '예천군' '광주시'
 '창원시마산합포구' '김제시' '곡성군' '청도군' '성북구' '과천시' '구례군' '부안군' '수원시권선구' '안산시단원구'
 '여주시' '여수시' '광양시' '사상구' '달성군' '나주시' '함평군' '세종' '고양시일산서구' '부평구' '무주군'
 '장성군' '청주시서원구' '영덕군' '창녕군' '완도군' '영암군' '미추홀구' '제천시' '안산시상록구' '춘천시' '오산시'
 '노원구' '하남시' '진천군' '통영시' '거창군' '이천시' '홍천군' '울진군' '포항시남구' '장수군' '창원시진해구'
 '화순군' '보은군' '의성군' '삼척시' '동래구' '산청군' '옥천군' '용산구' '하동군' '수원시영통구' '익산시'
 '군포시' '음성군' '고창군' '양평군' '계양구' '수성구' '영광군' '영천시' '서대문구' '연천군' '무안군' '속초시'
 '금정구' '안동시' '해운대구' '증평군' '전주시덕진구' '청송군' '임실군' '화천군' '보성군' '고흥군' '신안군'
 '계룡시' '횡성군' '봉화군' '함양군' '연제구' '태백시' '영월군' '용인시기흥구' '진도군' '홍성군' '평창군'
 '군위군' '용인시수지구' '양구군' '영도구' '담양군' '가평군' '울릉군' '청양군' '진안군' '영양군']

===== fire_firefighting.fire_type_1 =====
['건축' '임야' '기타(쓰레기 화재등)' '자동차' '위험물' '선박']

===== fire_firefighting.fire_type_2 =====
['구조물' nan '철도차량' '가스제조소등' '항공기']

===== fire_firefighting.ignition_factor_category_1 =====
['전기적 요인' '부주의' '기계적 요인' '미상' '방화의심' '기타' '방화' '교통사고' '가스누출(폭발)' '화학적 요인'
 '자연적인 요인' '제품결함']

===== fire_firefighting.ignition_factor_category_2 =====
['미확인단락' '가연물 근접방치' '담배꽁초' '과열/ 과부하' '음식물 조리중' '불씨/불꽃/화원방치' '접촉불량에 의한 단락'
 '절연열화에 의한 단락' '미상' '쓰레기 소각' '방화의심' '역화' '기타(기계적요인)' '기타' '과부하/과전류' '방화'
 '누전/지락' '기타(부주의)' '용접/ 절단/ 연마' '트래킹에 의한 단락' '압착/손상에 의한 단락' '노후' '정비불량'
 '빨래삶기' '오일/연료누설' '폭죽놀이' '교통사고' '논/임야태우기' '기타(전기적요인)' '반단선' '불장난'
 '가스누출(폭발)' '자동제어 실패' '유류 취급중' '화학적 폭발' '자연발화' '기타(화학적요인)' '층간단락'
 '화학적 발화(유증기 확산)' '기타(자연적인요인)' '혼촉발화' '수동제어 실패' '금수성물질의 물과 접촉' '자연적 재해'
 '돋보기 효과' '기기(전기/ 기계 등) 사용.설치부주의' '설계상결함' '기타(제품결함)' '제조상결함']

===== fire_firefighting.casualties =====
[  1   0   2   3  11   4   7  10 190   9   8   6   5  14  15  18  12  33
  44  32  59  42  50  30  13  17  19  48  16  52  38  23]

===== fire_firefighting.dead =====
[ 0  1  2  6 39  3  4  9  7 38  5]

===== fire_firefighting.injury =====
[  1   0   2   3  11   7   4 151   9   8   6   5  14  15  18  12  30  41
  32  10  56  42  27  16  17  19  13  33  43  47  37  23]

===== fire_firefighting.property_damage =====
[24099  2758    28 ... 60169 45183 13495]

===== fire_firefighting.location_category_1 =====
['주거' '임야' '기타' '생활서비스' '기타서비스' '산업시설' '판매/업무시설' '자동차/철도차량' '운수자동차시설'
 '교육시설' '집합시설' '위험물/가스제조소' '의료/복지시설' '선박/항공기' '문화재시설']

===== fire_firefighting.location_category_2 =====
['단독주택' '산불' '공동주택' '야외' '음식점' '일상서비스' '기타건축물' '동식물시설' '위생시설' '숙박시설'
 '기타주택' '창고시설' '들불' '자동차' '판매시설' '일반업무' '건설기계' '농업기계' '작업장' '공장시설' '자동차시설'
 '연구/학원' '종교시설' '군사시설' '위험물제조소등' '학교' '오락시설' '도로' '공연장' '발전시설' '건강시설'
 '공공기관' '운동시설' '노유자시설' '의료시설' '위락시설' '선박' '역사/터미널' '관람장' '전시장' '문화재'
 '청소년시설' '가스제조소등' '항공시설' '군용차량' '철도차량' '항만시설' '지중시설' '교정시설' '항공기']

===== fire_firefighting.location_category_3 =====
['상가주택(주택부분에서 화재가 발생한 경우에만 해당)' '단독주택' '공유림' '다세대주택' '기타야외' '일반주점' '의류'
 '아파트' '쓰레기' '사유림' '기타 건축물' '기타 동식물시설' '횟집' '양수장/ 정수장' '여관' '컨테이너(주거용)'
 '창고/ 물품저장소' '들판' '승용자동차' '상점가' '커피숍/다방/카페(휴게)' '버스' '한식' '다가구주택' '오피스텔'
 '모텔' '기타 건설기계' '기타 주택' '경운기' '기타 작업장' '치킨/족발' '그 밖의 공업' '농예용 온실' '다중주택'
 '기타 들불' '제과점/빵집/떡집(휴게)' '자동차검사장/ 매매장/ 부속상/ 정비공장' '일반상점' '일반학원' '교육원'
 '기타 창고' '세탁소' '공터' '기타 공동주택' '기타 일상서비스' '기숙사' '화물자동차' '시장' '고시원(원룸텔)'
 '기타 판매시설' '덤프트럭' '사찰' '일반회사' '인쇄업' '기타 군사시설' '볏짚' '우사' '야적장' '기타 위험물제조소'
 '일반빌딩' '식료품공업' '상가빌딩' '기타 승합자동차' '고등학교' '분식' '굴삭기' '버섯재배사' '연립주택' '호프집'
 '기타 단독주택' '노래연습장' '가로등' '대학교' '중식' '비닐하우스' '극장' '발전소(수력/ 화력)' '폐기물재활용시설'
 '금속기계 및 기구공업' '전통시장' '숲' '제재 및 목공업' '치킨/족발(휴게)' '고철처리소/ 고물상' '철물점'
 '전기/ 전자공업' '교회' '화학공업' '기타도로' '국유림' '기타 건강시설' '논밭두렁' '돈사' '펄프 및 제지공업'
 '특수자동차' '커피숍/다방/카페' '농장' '일식' '간이음식점' '방직공업' '폐기물처리시설' '공중화장실'
 '기타 일반업무시설' '소형 승합차' '냉장/ 냉동창고' '노상매점' '분식(휴게)' '문방구' '수리/A/S/상하수도'
 'PC방(인터넷게임제공업)' '이미용실' '펜션' '국가 및 지방자치단체 청사' '기타 연구/학원' '기타 숙박시설'
 '주상복합아파트' '계사' '기타 공연장' '할인점(마트)' '기타 운동시설' '아동복지시설' '쇼핑센터' '기타 음식점' '양식'
 '당구장' '외국어학원' '기타 오락시설' '종합병원' '캠핑용 자동차/트레일러' '유흥주점' '기도원' '목장' '병원'
 '기타 자동차시설' '공업사' '목욕장(사우나/ 찜질방)' '카센터' '단란주점' '기타 공공기관' '특수학교' '바지선'
 '지하상가' '패스트푸드' '기타 발전시설' '인쇄소' '철도역사' '어선' '요양시설' '기타 위생시설' '횟집(휴게)'
 '골프장' '요양소' '양식(휴게)' '부동산 중개업소' '기타 선박' '변압기' '유치원' '민박' '세차장/ 폐차장'
 '석유공업' '산장' '의원' '꽃집(화원)' '금융기관(농협 등)' '전봇대' '중학교' '체력단련장(헬스장)' '기타 농업기계'
 '테니스장/ 정구장' '공사' '오토바이' '콘도미니엄' '호텔' '초등학교' '화장품' '광업' '모닥불' '독서실' '과수원'
 '골프연습장' '주유취급소' '목공소/ 건재상' '노인복지시설' '묘지' '여인숙' '기타 종교시설' '패스트푸드(휴게)'
 '한의원' '예체능학원' '주차장' '한식(휴게)' '연구소' '기타 의료시설' '어린이집' '철공소' '편의점'
 '요업 및 토석공업' '치과병원' '유람선' '예식장' '수영장' '중식(휴게)' '승마장' '경로당' '볼링장' '정신병원'
 '사진관' '기타 위락시설' '체육관' '트랙터' '성당' '기타 관람장' '정미소' '백화점' '관망탑' '모델하우스'
 '실내야구장' '제조소' '마사지(안마/ 지압 등)' '분뇨시설' '게임제공업' '자동차운전학원/ 자동차정비학원' '수족관'
 '목초지' '제과점' '관리사무소' '포장마차' '에어로빅장' '하역장' '동물병원' '장례식장' '스크린골프연습장' '운동장'
 '기타 전시장' '약국' '공원' '공중전화박스' '국가지정문화재' '휴게텔(수면방)' 'Convention Center'
 '생활권수련시설(청소년수련관/ 청소년문화의집 등)' '화물터미널' '기타 역사/터미널' '기타휴게음식점' '기타 학교' '공관'
 '박물관' '군.경사격장' '시계/안경/금속점' '산후조리원' '기타 가스제조소' '기타 항공시설' '시도지정문화재' '탁구장'
 '수도원' '기원' '옥외탱크저장소' '콜라텍' '사회복지시설' '간이음식점(휴게)' '화물선' '경기장' '직업훈련소'
 '지하철역사' '유조선' '기계장치의 주차시설' '기념관' '음악당' '마을회관' '여객자동차터미널' '멀티미디어콘텐츠'
 '장애인재활시설' '변전소' '연극장' '지하탱크저장소' '군용차량' '판매취급소' '기타 문화재' '전동차' '도축장' '서점'
 '도서관' '옥내저장소' '사당' '미술관' '송/ 배전설비' '수녀원' '도계장' '산업전시장' '투전기업소 및 카지노업소'
 '조선소' '일반취급소' '연회장' '신문사' '기관차' '휴게소' '터널' '기타 노유자시설' '복합영상물제공업'
 '무도장 및 무도학원' '수상레저기구(보트등)' '특수작업선(해양관측선등)' '기타 청소년시설' '일식(휴게)' '교도소/ 구치소'
 '고압가스저장시설' '여객선' '기타 항만시설' '가스공급시설' '롤러스케이트장' '복합유통제공업' '온천장' '기타 지중시설'
 '기타 교정시설' '원자력발전소' '종합학원' '화장장' '이동탱크저장소' '비디오대여점' '체육도장(태권도/ 검도 등)'
 '근로복지시설' '기타 군용차량' '한방병원' '자연권수련시설(청소년수련원/ 청소년야영장 등)' '공동구' '막사' '옥외저장소'
 '외항선' '정부미도정공장' '여행객이용시설(공항)' '단식수련원/ 기수련원' '요가수련장' '레코드점' '고압가스제조시설'
 '박람회장' '비행기' '양로원' '종묘배양시설' '액화석유가스저장시설' '귀/손톱등 케어방' '숙박공유업' '태양광발전'
 '요양병원' '기타(철도차량)' '스케이트장' '태양열발전' '조력발전' '과학관' '외교공관 및 사택' '풍력발전'
 '연료전지발전설비' '여객이용시설' '옥내탱크저장소' '경마장' '경비행기' '함정(군함등)' '통신시설(관제소/ 송신소 등)'
 '기타 항공기' '키스방' '실내낚시터' '이착륙시설(활주로/ 유도등 등)' '실내사격장' '비디오감상실/ 비디오소극장'
 '회전익항공기(헬리콥터)' '전력구/ 통신구' '납골당' '이송취급소']

## 전처리 - firefighting 날짜, 시간 분리

In [12]:
fire_fighting_df.head()

,Unnamed: 0,fire_firefighting.num,fire_firefighting.year,fire_firefighting.tm,fire_firefighting.district_1,fire_firefighting.district_2,fire_firefighting.fire_type_1,fire_firefighting.fire_type_2,fire_firefighting.ignition_factor_category_1,fire_firefighting.ignition_factor_category_2,fire_firefighting.casualties,fire_firefighting.dead,fire_firefighting.injury,fire_firefighting.property_damage,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
0,1,1,2018,2018-01-01 00:03:00,경기도,고양시일산동구,건축,구조물,전기적 요인,미확인단락,1,0,1,24099,주거,단독주택,상가주택(주택부분에서 화재가 발생한 경우에만 해당)
1,2,2,2018,2018-01-01 00:12:00,전북특별자치도,완주군,건축,구조물,부주의,가연물 근접방치,0,0,0,2758,주거,단독주택,단독주택
2,3,3,2018,2018-01-01 00:16:00,경기도,남양주시,임야,NaN,부주의,담배꽁초,0,0,0,28,임야,산불,공유림
3,4,4,2018,2018-01-01 00:28:00,충청남도,보령시,건축,구조물,기계적 요인,과열/ 과부하,0,0,0,1942,주거,단독주택,단독주택
4,5,5,2018,2018-01-01 00:38:00,전라남도,순천시,건축,구조물,부주의,가연물 근접방치,0,0,0,1401,주거,단독주택,단독주택

In [16]:
# 화재 발생 date 분리 as datetime type
fire_fighting_df['fire_date'] = fire_fighting_df['fire_firefighting.tm'].apply(lambda x: pd.to_datetime(x.split()[0]))

In [19]:
# 그룹화를 위한 month 열 추출
fire_fighting_df['month'] = fire_fighting_df['fire_date'].apply(lambda x: x.month)

In [69]:
# 화재발생 시간 분리 as timestamp
fire_fighting_df['fire_firefighting.tm'] = fire_fighting_df['fire_firefighting.tm'].apply(lambda x: pd.to_datetime(x))
fire_fighting_df['fire_time'] = fire_fighting_df['fire_firefighting.tm'].apply(lambda x: x.strftime('%H:%M:%S'))

In [70]:
fire_fighting_df

,Unnamed: 0,fire_firefighting.num,fire_firefighting.year,fire_firefighting.tm,fire_firefighting.district_1,fire_firefighting.district_2,fire_firefighting.fire_type_1,fire_firefighting.fire_type_2,fire_firefighting.ignition_factor_category_1,fire_firefighting.ignition_factor_category_2,fire_firefighting.casualties,fire_firefighting.dead,fire_firefighting.injury,fire_firefighting.property_damage,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3,fire_date,month,fire_time
0,1,1,2018,2018-01-01 00:03:00,경기도,고양시일산동구,건축,구조물,전기적 요인,미확인단락,1,0,1,24099,주거,단독주택,상가주택(주택부분에서 화재가 발생한 경우에만 해당),2018-01-01,1,00:03:00
1,2,2,2018,2018-01-01 00:12:00,전북특별자치도,완주군,건축,구조물,부주의,가연물 근접방치,0,0,0,2758,주거,단독주택,단독주택,2018-01-01,1,00:12:00
2,3,3,2018,2018-01-01 00:16:00,경기도,남양주시,임야,NaN,부주의,담배꽁초,0,0,0,28,임야,산불,공유림,2018-01-01,1,00:16:00
3,4,4,2018,2018-01-01 00:28:00,충청남도,보령시,건축,구조물,기계적 요인,과열/ 과부하,0,0,0,1942,주거,단독주택,단독주택,2018-01-01,1,00:28:00
4,5,5,2018,2018-01-01 00:38:00,전라남도,순천시,건축,구조물,부주의,가연물 근접방치,0,0,0,1401,주거,단독주택,단독주택,2018-01-01,1,00:38:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236332,236333,38853,2023,2023-12-31 23:00:00,경상남도,양산시,건축,구조물,제품결함,제조상결함,0,0,0,99,판매/업무시설,일반업무,오피스텔,2023-12-31,12,23:00:00
236333,236334,38854,2023,2023-12-31 23:05:00,부산광역시,북구,건축,구조물,부주의,담배꽁초,0,0,0,30,주거,단독주택,단독주택,2023-12-31,12,23:05:00
236334,236335,38855,2023,2023-12-31 23:35:00,충청북도,영동군,건축,구조물,미상,미상,0,0,0,13495,주거,기타주택,기타 주택,2023-12-31,12,23:35:00
236335,236336,38856,2023,2023-12-31 23:48:00,서울특별시,성북구,건축,구조물,부주의,음식물 조리중,0,0,0,12,주거,공동주택,연립주택,2023-12-31,12,23:48:00
236336,236337,38857,2023,2023-12-31 23:50:00,경기도,김포시,건축,구조물,전기적 요인,절연열화에 의한 단락,0,0,0,3509,산업시설,공장시설,금속기계 및 기구공업,2023-12-31,12,23:50:00

In [21]:
import sys
sys.path.append(r'/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages')
import pygwalker as pyg

walker = pyg.walk(fire_fighting_df)

Box(children=(HTML(value='<div id="ifr-pyg-00061843633d8c90jJeOo7rgh0bzkQFt" style="height: auto">\n    <head>…

## 2. 지역별 연도별 화재발생 건수

In [43]:
# 지역별 & 연도별 group
fire_fighting_df.groupby(['fire_firefighting.district_1', 'fire_firefighting.year']).count()

# 지역별 연평균
group_sizes = fire_fighting_df.groupby(['fire_firefighting.district_1', 'fire_firefighting.year']).size()
result = group_sizes.groupby(level=0).mean()
result

fire_firefighting.district_1
강원특별자치도    1958.166667
경기도        8824.666667
경상남도       3288.166667
경상북도       2815.000000
광주광역시       803.666667
대구광역시      1334.500000
대전광역시       936.333333
부산광역시      2439.500000
서울특별시      5559.166667
세종특별자치시     210.833333
울산광역시       842.166667
인천광역시      1394.666667
전라남도       2626.333333
전북특별자치도    2121.333333
제주특별자치도     578.333333
충청남도       2170.833333
충청북도       1485.833333
dtype: float64

In [29]:
fire_fighting_df.count()

Unnamed: 0                                      236337
fire_firefighting.num                           236337
fire_firefighting.year                          236337
fire_firefighting.tm                            236337
fire_firefighting.district_1                    236337
fire_firefighting.district_2                    236337
fire_firefighting.fire_type_1                   236337
fire_firefighting.fire_type_2                   182619
fire_firefighting.ignition_factor_category_1    236337
fire_firefighting.ignition_factor_category_2    236337
fire_firefighting.casualties                    236337
fire_firefighting.dead                          236337
fire_firefighting.injury                        236337
fire_firefighting.property_damage               236337
fire_firefighting.location_category_1           236337
fire_firefighting.location_category_2           236337
fire_firefighting.location_category_3           236337
fire_date                                       236337
month                                           236337
dtype: int64

## 3. location category_1,2,3

In [55]:
# location 1, 2, 3 category 살펴보기
location_df = fire_fighting_df[['fire_firefighting.location_category_1', 'fire_firefighting.location_category_2', 'fire_firefighting.location_category_3']]

# unique row 뽑아내기 위해 duplicate 제거
location_unique = location_df.drop_duplicates()
# location category 1 리스트
location_list = location_unique['fire_firefighting.location_category_1'].unique()
# location catefory 1별 데이터프레임 display
for loc in location_list:
    display(location_unique[location_unique['fire_firefighting.location_category_1']==loc])
    print()

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
0,주거,단독주택,상가주택(주택부분에서 화재가 발생한 경우에만 해당)
1,주거,단독주택,단독주택
5,주거,공동주택,다세대주택
10,주거,공동주택,아파트
26,주거,기타주택,컨테이너(주거용)
41,주거,단독주택,다가구주택
54,주거,기타주택,기타 주택
73,주거,단독주택,다중주택
110,주거,공동주택,기타 공동주택
112,주거,공동주택,기숙사
189,주거,공동주택,연립주택
206,주거,단독주택,기타 단독주택
211,주거,기타주택,비닐하우스
624,주거,공동주택,주상복합아파트

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
2,임야,산불,공유림
13,임야,산불,사유림
29,임야,들불,들판
81,임야,들불,기타 들불
243,임야,들불,숲
292,임야,산불,국유림
318,임야,들불,논밭두렁
2189,임야,들불,과수원
2284,임야,들불,묘지
7266,임야,들불,목초지
11187,임야,들불,군.경사격장

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
7,기타,야외,기타야외
12,기타,야외,쓰레기
109,기타,야외,공터
137,기타,야외,볏짚
141,기타,야외,야적장
208,기타,도로,가로등
286,기타,도로,기타도로
1212,기타,도로,변압기
1480,기타,도로,전봇대
2118,기타,야외,모닥불

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
8,생활서비스,음식점,일반주점
9,생활서비스,일상서비스,의류
19,생활서비스,음식점,횟집
34,생활서비스,음식점,커피숍/다방/카페(휴게)
37,생활서비스,음식점,한식
...,...,...,...
40312,생활서비스,오락시설,복합유통제공업
46903,생활서비스,오락시설,비디오대여점
72501,생활서비스,일상서비스,레코드점
101872,생활서비스,일상서비스,귀/손톱등 케어방
162892,생활서비스,오락시설,키스방

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
14,기타서비스,기타건축물,기타 건축물
408,기타서비스,기타건축물,공중화장실
474,기타서비스,기타건축물,노상매점
7886,기타서비스,기타건축물,포장마차
9567,기타서비스,기타건축물,공중전화박스

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
16,산업시설,동식물시설,기타 동식물시설
21,산업시설,위생시설,양수장/ 정수장
28,산업시설,창고시설,창고/ 물품저장소
63,산업시설,작업장,기타 작업장
70,산업시설,공장시설,그 밖의 공업
71,산업시설,동식물시설,농예용 온실
96,산업시설,창고시설,기타 창고
132,산업시설,공장시설,인쇄업
140,산업시설,동식물시설,우사
156,산업시설,공장시설,식료품공업
183,산업시설,동식물시설,버섯재배사
223,산업시설,발전시설,발전소(수력/ 화력)
227,산업시설,위생시설,폐기물재활용시설
232,산업시설,공장시설,금속기계 및 기구공업
247,산업시설,공장시설,제재 및 목공업
256,산업시설,작업장,고철처리소/ 고물상
274,산업시설,공장시설,전기/ 전자공업
283,산업시설,공장시설,화학공업
335,산업시설,동식물시설,돈사
342,산업시설,공장시설,펄프 및 제지공업
350,산업시설,동식물시설,농장
384,산업시설,공장시설,방직공업
390,산업시설,위생시설,폐기물처리시설
450,산업시설,창고시설,냉장/ 냉동창고
626,산업시설,동식물시설,계사
853,산업시설,동식물시설,목장
880,산업시설,작업장,공업사
1067,산업시설,발전시설,기타 발전시설
1126,산업시설,위생시설,기타 위생시설
1313,산업시설,공장시설,석유공업
2040,산업시설,공장시설,광업
2241,산업시설,작업장,목공소/ 건재상
2830,산업시설,작업장,철공소
3062,산업시설,공장시설,요업 및 토석공업
5325,산업시설,작업장,정미소
6482,산업시설,위생시설,분뇨시설
7970,산업시설,창고시설,하역장
18635,산업시설,발전시설,변전소
21904,산업시설,동식물시설,도축장
24156,산업시설,발전시설,송/ 배전설비
25184,산업시설,동식물시설,도계장
30932,산업시설,지중시설,터널
41595,산업시설,지중시설,기타 지중시설
42646,산업시설,발전시설,원자력발전소
43644,산업시설,위생시설,화장장
54913,산업시설,지중시설,공동구
65041,산업시설,작업장,정부미도정공장
90401,산업시설,위생시설,종묘배양시설
103930,산업시설,발전시설,태양광발전
108953,산업시설,발전시설,태양열발전
109002,산업시설,발전시설,조력발전
127604,산업시설,발전시설,풍력발전
129513,산업시설,발전시설,연료전지발전설비
197015,산업시설,지중시설,전력구/ 통신구
227046,산업시설,위생시설,납골당

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
24,판매/업무시설,숙박시설,여관
32,판매/업무시설,판매시설,상점가
44,판매/업무시설,일반업무,오피스텔
45,판매/업무시설,숙박시설,모텔
115,판매/업무시설,판매시설,시장
124,판매/업무시설,판매시설,기타 판매시설
129,판매/업무시설,일반업무,일반회사
133,판매/업무시설,군사시설,기타 군사시설
154,판매/업무시설,일반업무,일반빌딩
157,판매/업무시설,판매시설,상가빌딩
238,판매/업무시설,판매시설,전통시장
427,판매/업무시설,일반업무,기타 일반업무시설
532,판매/업무시설,숙박시설,펜션
540,판매/업무시설,공공기관,국가 및 지방자치단체 청사
607,판매/업무시설,숙박시설,기타 숙박시설
638,판매/업무시설,판매시설,할인점(마트)
711,판매/업무시설,판매시설,쇼핑센터
945,판매/업무시설,공공기관,기타 공공기관
999,판매/업무시설,판매시설,지하상가
1292,판매/업무시설,숙박시설,민박
1369,판매/업무시설,숙박시설,산장
1440,판매/업무시설,일반업무,금융기관(농협 등)
1712,판매/업무시설,일반업무,공사
1816,판매/업무시설,숙박시설,콘도미니엄
1860,판매/업무시설,숙박시설,호텔
2318,판매/업무시설,숙박시설,여인숙
5513,판매/업무시설,판매시설,백화점
10293,판매/업무시설,청소년시설,생활권수련시설(청소년수련관/ 청소년문화의집 등)
11044,판매/업무시설,공공기관,공관
27892,판매/업무시설,일반업무,신문사
34627,판매/업무시설,청소년시설,기타 청소년시설
35269,판매/업무시설,교정시설,교도소/ 구치소
42521,판매/업무시설,교정시설,기타 교정시설
53716,판매/업무시설,청소년시설,자연권수련시설(청소년수련원/ 청소년야영장 등)
57012,판매/업무시설,군사시설,막사
102610,판매/업무시설,숙박시설,숙박공유업
124956,판매/업무시설,공공기관,외교공관 및 사택

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
30,자동차/철도차량,자동차,승용자동차
35,자동차/철도차량,자동차,버스
51,자동차/철도차량,건설기계,기타 건설기계
58,자동차/철도차량,농업기계,경운기
113,자동차/철도차량,자동차,화물자동차
126,자동차/철도차량,건설기계,덤프트럭
166,자동차/철도차량,자동차,기타 승합자동차
178,자동차/철도차량,건설기계,굴삭기
347,자동차/철도차량,자동차,특수자동차
445,자동차/철도차량,자동차,소형 승합차
822,자동차/철도차량,자동차,캠핑용 자동차/트레일러
1559,자동차/철도차량,농업기계,기타 농업기계
1772,자동차/철도차량,자동차,오토바이
4455,자동차/철도차량,농업기계,트랙터
19203,자동차/철도차량,군용차량,군용차량
21709,자동차/철도차량,철도차량,전동차
29530,자동차/철도차량,철도차량,기관차
51971,자동차/철도차량,군용차량,기타 군용차량
107744,자동차/철도차량,철도차량,기타(철도차량)

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
83,운수자동차시설,자동차시설,자동차검사장/ 매매장/ 부속상/ 정비공장
863,운수자동차시설,자동차시설,기타 자동차시설
936,운수자동차시설,자동차시설,카센터
1076,운수자동차시설,역사/터미널,철도역사
1297,운수자동차시설,자동차시설,세차장/ 폐차장
2548,운수자동차시설,자동차시설,주차장
6961,운수자동차시설,자동차시설,자동차운전학원/ 자동차정비학원
10590,운수자동차시설,역사/터미널,화물터미널
10622,운수자동차시설,역사/터미널,기타 역사/터미널
11505,운수자동차시설,항공시설,기타 항공시설
14113,운수자동차시설,역사/터미널,지하철역사
14473,운수자동차시설,자동차시설,기계장치의 주차시설
17727,운수자동차시설,역사/터미널,여객자동차터미널
25815,운수자동차시설,항만시설,조선소
30588,운수자동차시설,역사/터미널,휴게소
37712,운수자동차시설,항만시설,기타 항만시설
68755,운수자동차시설,항공시설,여행객이용시설(공항)
139026,운수자동차시설,항만시설,여객이용시설
149896,운수자동차시설,항공시설,통신시설(관제소/ 송신소 등)
168762,운수자동차시설,항공시설,이착륙시설(활주로/ 유도등 등)

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
90,교육시설,연구/학원,일반학원
93,교육시설,연구/학원,교육원
172,교육시설,학교,고등학교
209,교육시설,학교,대학교
575,교육시설,연구/학원,기타 연구/학원
788,교육시설,연구/학원,외국어학원
962,교육시설,학교,특수학교
1523,교육시설,학교,중학교
1959,교육시설,학교,초등학교
2520,교육시설,연구/학원,예체능학원
2605,교육시설,연구/학원,연구소
10887,교육시설,학교,기타 학교
14021,교육시설,학교,직업훈련소
23247,교육시설,연구/학원,도서관
42998,교육시설,연구/학원,종합학원

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
127,집합시설,종교시설,사찰
215,집합시설,공연장,극장
275,집합시설,종교시설,교회
636,집합시설,공연장,기타 공연장
700,집합시설,운동시설,기타 운동시설
740,집합시설,운동시설,당구장
852,집합시설,종교시설,기도원
1160,집합시설,운동시설,골프장
1527,집합시설,운동시설,체력단련장(헬스장)
1662,집합시설,운동시설,테니스장/ 정구장
2230,집합시설,운동시설,골프연습장
2342,집합시설,종교시설,기타 종교시설
3444,집합시설,운동시설,수영장
3590,집합시설,운동시설,승마장
3976,집합시설,운동시설,볼링장
4407,집합시설,관람장,체육관
4670,집합시설,종교시설,성당
5166,집합시설,관람장,기타 관람장
5515,집합시설,관람장,관망탑
5659,집합시설,전시장,모델하우스
5730,집합시설,운동시설,실내야구장
7100,집합시설,관람장,수족관
7916,집합시설,운동시설,에어로빅장
8862,집합시설,운동시설,스크린골프연습장
8968,집합시설,운동시설,운동장
9011,집합시설,전시장,기타 전시장
9419,집합시설,관람장,공원
9656,집합시설,관람장,Convention Center
11168,집합시설,전시장,박물관
11690,집합시설,운동시설,탁구장
11883,집합시설,종교시설,수도원
13480,집합시설,관람장,경기장
14669,집합시설,전시장,기념관
15501,집합시설,공연장,음악당
18744,집합시설,공연장,연극장
23578,집합시설,종교시설,사당
24090,집합시설,전시장,미술관
24885,집합시설,종교시설,수녀원
25204,집합시설,전시장,산업전시장
32362,집합시설,공연장,복합영상물제공업
38341,집합시설,운동시설,롤러스케이트장
49420,집합시설,운동시설,체육도장(태권도/ 검도 등)
73507,집합시설,전시장,박람회장
108561,집합시설,운동시설,스케이트장
124360,집합시설,전시장,과학관
141440,집합시설,관람장,경마장
163916,집합시설,운동시설,실내낚시터
177770,집합시설,운동시설,실내사격장
180498,집합시설,공연장,비디오감상실/ 비디오소극장

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
147,위험물/가스제조소,위험물제조소등,기타 위험물제조소
2235,위험물/가스제조소,위험물제조소등,주유취급소
6094,위험물/가스제조소,위험물제조소등,제조소
11375,위험물/가스제조소,가스제조소등,기타 가스제조소
13055,위험물/가스제조소,위험물제조소등,옥외탱크저장소
19118,위험물/가스제조소,위험물제조소등,지하탱크저장소
20163,위험물/가스제조소,위험물제조소등,판매취급소
23264,위험물/가스제조소,위험물제조소등,옥내저장소
26247,위험물/가스제조소,위험물제조소등,일반취급소
35406,위험물/가스제조소,가스제조소등,고압가스저장시설
38191,위험물/가스제조소,가스제조소등,가스공급시설
46513,위험물/가스제조소,위험물제조소등,이동탱크저장소
58492,위험물/가스제조소,위험물제조소등,옥외저장소
72793,위험물/가스제조소,가스제조소등,고압가스제조시설
101692,위험물/가스제조소,가스제조소등,액화석유가스저장시설
141375,위험물/가스제조소,위험물제조소등,옥내탱크저장소
234442,위험물/가스제조소,위험물제조소등,이송취급소

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
297,의료/복지시설,건강시설,기타 건강시설
705,의료/복지시설,노유자시설,아동복지시설
803,의료/복지시설,의료시설,종합병원
857,의료/복지시설,의료시설,병원
882,의료/복지시설,건강시설,목욕장(사우나/ 찜질방)
1111,의료/복지시설,노유자시설,요양시설
1169,의료/복지시설,의료시설,요양소
1268,의료/복지시설,노유자시설,유치원
1392,의료/복지시설,의료시설,의원
2273,의료/복지시설,노유자시설,노인복지시설
2498,의료/복지시설,의료시설,한의원
2611,의료/복지시설,의료시설,기타 의료시설
2751,의료/복지시설,노유자시설,어린이집
3105,의료/복지시설,의료시설,치과병원
3943,의료/복지시설,노유자시설,경로당
4155,의료/복지시설,의료시설,정신병원
6472,의료/복지시설,건강시설,마사지(안마/ 지압 등)
8382,의료/복지시설,의료시설,동물병원
8575,의료/복지시설,의료시설,장례식장
9286,의료/복지시설,의료시설,약국
11225,의료/복지시설,의료시설,산후조리원
13228,의료/복지시설,노유자시설,사회복지시설
18528,의료/복지시설,노유자시설,장애인재활시설
30949,의료/복지시설,노유자시설,기타 노유자시설
41510,의료/복지시설,건강시설,온천장
50846,의료/복지시설,노유자시설,근로복지시설
52317,의료/복지시설,의료시설,한방병원
69998,의료/복지시설,건강시설,단식수련원/ 기수련원
70047,의료/복지시설,건강시설,요가수련장
81965,의료/복지시설,노유자시설,양로원
104091,의료/복지시설,의료시설,요양병원

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
980,선박/항공기,선박,바지선
1078,선박/항공기,선박,어선
1185,선박/항공기,선박,기타 선박
3219,선박/항공기,선박,유람선
13406,선박/항공기,선박,화물선
14317,선박/항공기,선박,유조선
33580,선박/항공기,선박,수상레저기구(보트등)
33930,선박/항공기,선박,특수작업선(해양관측선등)
36164,선박/항공기,선박,여객선
61579,선박/항공기,선박,외항선
75061,선박/항공기,항공기,비행기
141441,선박/항공기,항공기,경비행기
144528,선박/항공기,선박,함정(군함등)
158731,선박/항공기,항공기,기타 항공기
193386,선박/항공기,항공기,회전익항공기(헬리콥터)

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
9648,문화재시설,문화재,국가지정문화재
11686,문화재시설,문화재,시도지정문화재
20504,문화재시설,문화재,기타 문화재

In [57]:
# location category 1 == 생활서비스
loc_list = location_zunique['fire_firefighting.location_category_2'].unique()
for loc in loc_list:
    display(location_unique[location_unique['fire_firefighting.location_category_2']==loc])
    print()

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
0,주거,단독주택,상가주택(주택부분에서 화재가 발생한 경우에만 해당)
1,주거,단독주택,단독주택
41,주거,단독주택,다가구주택
73,주거,단독주택,다중주택
206,주거,단독주택,기타 단독주택

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
2,임야,산불,공유림
13,임야,산불,사유림
292,임야,산불,국유림

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
5,주거,공동주택,다세대주택
10,주거,공동주택,아파트
110,주거,공동주택,기타 공동주택
112,주거,공동주택,기숙사
189,주거,공동주택,연립주택
624,주거,공동주택,주상복합아파트

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
7,기타,야외,기타야외
12,기타,야외,쓰레기
109,기타,야외,공터
137,기타,야외,볏짚
141,기타,야외,야적장
2118,기타,야외,모닥불

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
8,생활서비스,음식점,일반주점
19,생활서비스,음식점,횟집
34,생활서비스,음식점,커피숍/다방/카페(휴게)
37,생활서비스,음식점,한식
64,생활서비스,음식점,치킨/족발
82,생활서비스,음식점,제과점/빵집/떡집(휴게)
177,생활서비스,음식점,분식
194,생활서비스,음식점,호프집
210,생활서비스,음식점,중식
249,생활서비스,음식점,치킨/족발(휴게)
348,생활서비스,음식점,커피숍/다방/카페
358,생활서비스,음식점,일식
368,생활서비스,음식점,간이음식점
476,생활서비스,음식점,분식(휴게)
729,생활서비스,음식점,기타 음식점
732,생활서비스,음식점,양식
1019,생활서비스,음식점,패스트푸드
1152,생활서비스,음식점,횟집(휴게)
1179,생활서비스,음식점,양식(휴게)
2467,생활서비스,음식점,패스트푸드(휴게)
2552,생활서비스,음식점,한식(휴게)
3445,생활서비스,음식점,중식(휴게)
7288,생활서비스,음식점,제과점
10786,생활서비스,음식점,기타휴게음식점
13276,생활서비스,음식점,간이음식점(휴게)
35116,생활서비스,음식점,일식(휴게)

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
9,생활서비스,일상서비스,의류
89,생활서비스,일상서비스,일반상점
107,생활서비스,일상서비스,세탁소
111,생활서비스,일상서비스,기타 일상서비스
123,생활서비스,일상서비스,고시원(원룸텔)
258,생활서비스,일상서비스,철물점
485,생활서비스,일상서비스,문방구
492,생활서비스,일상서비스,수리/A/S/상하수도
519,생활서비스,일상서비스,이미용실
1075,생활서비스,일상서비스,인쇄소
1184,생활서비스,일상서비스,부동산 중개업소
1436,생활서비스,일상서비스,꽃집(화원)
1995,생활서비스,일상서비스,화장품
2131,생활서비스,일상서비스,독서실
3035,생활서비스,일상서비스,편의점
3290,생활서비스,일상서비스,예식장
4258,생활서비스,일상서비스,사진관
7389,생활서비스,일상서비스,관리사무소
9650,생활서비스,일상서비스,휴게텔(수면방)
11216,생활서비스,일상서비스,시계/안경/금속점
12094,생활서비스,일상서비스,기원
15653,생활서비스,일상서비스,마을회관
22887,생활서비스,일상서비스,서점
26998,생활서비스,일상서비스,연회장
72501,생활서비스,일상서비스,레코드점
101872,생활서비스,일상서비스,귀/손톱등 케어방

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
14,기타서비스,기타건축물,기타 건축물
408,기타서비스,기타건축물,공중화장실
474,기타서비스,기타건축물,노상매점
7886,기타서비스,기타건축물,포장마차
9567,기타서비스,기타건축물,공중전화박스

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
16,산업시설,동식물시설,기타 동식물시설
71,산업시설,동식물시설,농예용 온실
140,산업시설,동식물시설,우사
183,산업시설,동식물시설,버섯재배사
335,산업시설,동식물시설,돈사
350,산업시설,동식물시설,농장
626,산업시설,동식물시설,계사
853,산업시설,동식물시설,목장
21904,산업시설,동식물시설,도축장
25184,산업시설,동식물시설,도계장

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
21,산업시설,위생시설,양수장/ 정수장
227,산업시설,위생시설,폐기물재활용시설
390,산업시설,위생시설,폐기물처리시설
1126,산업시설,위생시설,기타 위생시설
6482,산업시설,위생시설,분뇨시설
43644,산업시설,위생시설,화장장
90401,산업시설,위생시설,종묘배양시설
227046,산업시설,위생시설,납골당

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
24,판매/업무시설,숙박시설,여관
45,판매/업무시설,숙박시설,모텔
532,판매/업무시설,숙박시설,펜션
607,판매/업무시설,숙박시설,기타 숙박시설
1292,판매/업무시설,숙박시설,민박
1369,판매/업무시설,숙박시설,산장
1816,판매/업무시설,숙박시설,콘도미니엄
1860,판매/업무시설,숙박시설,호텔
2318,판매/업무시설,숙박시설,여인숙
102610,판매/업무시설,숙박시설,숙박공유업

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
26,주거,기타주택,컨테이너(주거용)
54,주거,기타주택,기타 주택
211,주거,기타주택,비닐하우스

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
28,산업시설,창고시설,창고/ 물품저장소
96,산업시설,창고시설,기타 창고
450,산업시설,창고시설,냉장/ 냉동창고
7970,산업시설,창고시설,하역장

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
29,임야,들불,들판
81,임야,들불,기타 들불
243,임야,들불,숲
318,임야,들불,논밭두렁
2189,임야,들불,과수원
2284,임야,들불,묘지
7266,임야,들불,목초지
11187,임야,들불,군.경사격장

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
30,자동차/철도차량,자동차,승용자동차
35,자동차/철도차량,자동차,버스
113,자동차/철도차량,자동차,화물자동차
166,자동차/철도차량,자동차,기타 승합자동차
347,자동차/철도차량,자동차,특수자동차
445,자동차/철도차량,자동차,소형 승합차
822,자동차/철도차량,자동차,캠핑용 자동차/트레일러
1772,자동차/철도차량,자동차,오토바이

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
32,판매/업무시설,판매시설,상점가
115,판매/업무시설,판매시설,시장
124,판매/업무시설,판매시설,기타 판매시설
157,판매/업무시설,판매시설,상가빌딩
238,판매/업무시설,판매시설,전통시장
638,판매/업무시설,판매시설,할인점(마트)
711,판매/업무시설,판매시설,쇼핑센터
999,판매/업무시설,판매시설,지하상가
5513,판매/업무시설,판매시설,백화점

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
44,판매/업무시설,일반업무,오피스텔
129,판매/업무시설,일반업무,일반회사
154,판매/업무시설,일반업무,일반빌딩
427,판매/업무시설,일반업무,기타 일반업무시설
1440,판매/업무시설,일반업무,금융기관(농협 등)
1712,판매/업무시설,일반업무,공사
27892,판매/업무시설,일반업무,신문사

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
51,자동차/철도차량,건설기계,기타 건설기계
126,자동차/철도차량,건설기계,덤프트럭
178,자동차/철도차량,건설기계,굴삭기

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
58,자동차/철도차량,농업기계,경운기
1559,자동차/철도차량,농업기계,기타 농업기계
4455,자동차/철도차량,농업기계,트랙터

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
63,산업시설,작업장,기타 작업장
256,산업시설,작업장,고철처리소/ 고물상
880,산업시설,작업장,공업사
2241,산업시설,작업장,목공소/ 건재상
2830,산업시설,작업장,철공소
5325,산업시설,작업장,정미소
65041,산업시설,작업장,정부미도정공장

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
70,산업시설,공장시설,그 밖의 공업
132,산업시설,공장시설,인쇄업
156,산업시설,공장시설,식료품공업
232,산업시설,공장시설,금속기계 및 기구공업
247,산업시설,공장시설,제재 및 목공업
274,산업시설,공장시설,전기/ 전자공업
283,산업시설,공장시설,화학공업
342,산업시설,공장시설,펄프 및 제지공업
384,산업시설,공장시설,방직공업
1313,산업시설,공장시설,석유공업
2040,산업시설,공장시설,광업
3062,산업시설,공장시설,요업 및 토석공업

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
83,운수자동차시설,자동차시설,자동차검사장/ 매매장/ 부속상/ 정비공장
863,운수자동차시설,자동차시설,기타 자동차시설
936,운수자동차시설,자동차시설,카센터
1297,운수자동차시설,자동차시설,세차장/ 폐차장
2548,운수자동차시설,자동차시설,주차장
6961,운수자동차시설,자동차시설,자동차운전학원/ 자동차정비학원
14473,운수자동차시설,자동차시설,기계장치의 주차시설

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
90,교육시설,연구/학원,일반학원
93,교육시설,연구/학원,교육원
575,교육시설,연구/학원,기타 연구/학원
788,교육시설,연구/학원,외국어학원
2520,교육시설,연구/학원,예체능학원
2605,교육시설,연구/학원,연구소
23247,교육시설,연구/학원,도서관
42998,교육시설,연구/학원,종합학원

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
127,집합시설,종교시설,사찰
275,집합시설,종교시설,교회
852,집합시설,종교시설,기도원
2342,집합시설,종교시설,기타 종교시설
4670,집합시설,종교시설,성당
11883,집합시설,종교시설,수도원
23578,집합시설,종교시설,사당
24885,집합시설,종교시설,수녀원

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
133,판매/업무시설,군사시설,기타 군사시설
57012,판매/업무시설,군사시설,막사

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
147,위험물/가스제조소,위험물제조소등,기타 위험물제조소
2235,위험물/가스제조소,위험물제조소등,주유취급소
6094,위험물/가스제조소,위험물제조소등,제조소
13055,위험물/가스제조소,위험물제조소등,옥외탱크저장소
19118,위험물/가스제조소,위험물제조소등,지하탱크저장소
20163,위험물/가스제조소,위험물제조소등,판매취급소
23264,위험물/가스제조소,위험물제조소등,옥내저장소
26247,위험물/가스제조소,위험물제조소등,일반취급소
46513,위험물/가스제조소,위험물제조소등,이동탱크저장소
58492,위험물/가스제조소,위험물제조소등,옥외저장소
141375,위험물/가스제조소,위험물제조소등,옥내탱크저장소
234442,위험물/가스제조소,위험물제조소등,이송취급소

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
172,교육시설,학교,고등학교
209,교육시설,학교,대학교
962,교육시설,학교,특수학교
1523,교육시설,학교,중학교
1959,교육시설,학교,초등학교
10887,교육시설,학교,기타 학교
14021,교육시설,학교,직업훈련소

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
207,생활서비스,오락시설,노래연습장
514,생활서비스,오락시설,PC방(인터넷게임제공업)
791,생활서비스,오락시설,기타 오락시설
6947,생활서비스,오락시설,게임제공업
13095,생활서비스,오락시설,콜라텍
18334,생활서비스,오락시설,멀티미디어콘텐츠
40312,생활서비스,오락시설,복합유통제공업
46903,생활서비스,오락시설,비디오대여점
162892,생활서비스,오락시설,키스방

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
208,기타,도로,가로등
286,기타,도로,기타도로
1212,기타,도로,변압기
1480,기타,도로,전봇대

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
215,집합시설,공연장,극장
636,집합시설,공연장,기타 공연장
15501,집합시설,공연장,음악당
18744,집합시설,공연장,연극장
32362,집합시설,공연장,복합영상물제공업
180498,집합시설,공연장,비디오감상실/ 비디오소극장

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
223,산업시설,발전시설,발전소(수력/ 화력)
1067,산업시설,발전시설,기타 발전시설
18635,산업시설,발전시설,변전소
24156,산업시설,발전시설,송/ 배전설비
42646,산업시설,발전시설,원자력발전소
103930,산업시설,발전시설,태양광발전
108953,산업시설,발전시설,태양열발전
109002,산업시설,발전시설,조력발전
127604,산업시설,발전시설,풍력발전
129513,산업시설,발전시설,연료전지발전설비

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
297,의료/복지시설,건강시설,기타 건강시설
882,의료/복지시설,건강시설,목욕장(사우나/ 찜질방)
6472,의료/복지시설,건강시설,마사지(안마/ 지압 등)
41510,의료/복지시설,건강시설,온천장
69998,의료/복지시설,건강시설,단식수련원/ 기수련원
70047,의료/복지시설,건강시설,요가수련장

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
540,판매/업무시설,공공기관,국가 및 지방자치단체 청사
945,판매/업무시설,공공기관,기타 공공기관
11044,판매/업무시설,공공기관,공관
124956,판매/업무시설,공공기관,외교공관 및 사택

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
700,집합시설,운동시설,기타 운동시설
740,집합시설,운동시설,당구장
1160,집합시설,운동시설,골프장
1527,집합시설,운동시설,체력단련장(헬스장)
1662,집합시설,운동시설,테니스장/ 정구장
2230,집합시설,운동시설,골프연습장
3444,집합시설,운동시설,수영장
3590,집합시설,운동시설,승마장
3976,집합시설,운동시설,볼링장
5730,집합시설,운동시설,실내야구장
7916,집합시설,운동시설,에어로빅장
8862,집합시설,운동시설,스크린골프연습장
8968,집합시설,운동시설,운동장
11690,집합시설,운동시설,탁구장
38341,집합시설,운동시설,롤러스케이트장
49420,집합시설,운동시설,체육도장(태권도/ 검도 등)
108561,집합시설,운동시설,스케이트장
163916,집합시설,운동시설,실내낚시터
177770,집합시설,운동시설,실내사격장

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
705,의료/복지시설,노유자시설,아동복지시설
1111,의료/복지시설,노유자시설,요양시설
1268,의료/복지시설,노유자시설,유치원
2273,의료/복지시설,노유자시설,노인복지시설
2751,의료/복지시설,노유자시설,어린이집
3943,의료/복지시설,노유자시설,경로당
13228,의료/복지시설,노유자시설,사회복지시설
18528,의료/복지시설,노유자시설,장애인재활시설
30949,의료/복지시설,노유자시설,기타 노유자시설
50846,의료/복지시설,노유자시설,근로복지시설
81965,의료/복지시설,노유자시설,양로원

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
803,의료/복지시설,의료시설,종합병원
857,의료/복지시설,의료시설,병원
1169,의료/복지시설,의료시설,요양소
1392,의료/복지시설,의료시설,의원
2498,의료/복지시설,의료시설,한의원
2611,의료/복지시설,의료시설,기타 의료시설
3105,의료/복지시설,의료시설,치과병원
4155,의료/복지시설,의료시설,정신병원
8382,의료/복지시설,의료시설,동물병원
8575,의료/복지시설,의료시설,장례식장
9286,의료/복지시설,의료시설,약국
11225,의료/복지시설,의료시설,산후조리원
52317,의료/복지시설,의료시설,한방병원
104091,의료/복지시설,의료시설,요양병원

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
846,생활서비스,위락시설,유흥주점
939,생활서비스,위락시설,단란주점
4388,생활서비스,위락시설,기타 위락시설
25322,생활서비스,위락시설,투전기업소 및 카지노업소
32955,생활서비스,위락시설,무도장 및 무도학원

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
980,선박/항공기,선박,바지선
1078,선박/항공기,선박,어선
1185,선박/항공기,선박,기타 선박
3219,선박/항공기,선박,유람선
13406,선박/항공기,선박,화물선
14317,선박/항공기,선박,유조선
33580,선박/항공기,선박,수상레저기구(보트등)
33930,선박/항공기,선박,특수작업선(해양관측선등)
36164,선박/항공기,선박,여객선
61579,선박/항공기,선박,외항선
144528,선박/항공기,선박,함정(군함등)

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
1076,운수자동차시설,역사/터미널,철도역사
10590,운수자동차시설,역사/터미널,화물터미널
10622,운수자동차시설,역사/터미널,기타 역사/터미널
14113,운수자동차시설,역사/터미널,지하철역사
17727,운수자동차시설,역사/터미널,여객자동차터미널
30588,운수자동차시설,역사/터미널,휴게소

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
4407,집합시설,관람장,체육관
5166,집합시설,관람장,기타 관람장
5515,집합시설,관람장,관망탑
7100,집합시설,관람장,수족관
9419,집합시설,관람장,공원
9656,집합시설,관람장,Convention Center
13480,집합시설,관람장,경기장
141440,집합시설,관람장,경마장

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
5659,집합시설,전시장,모델하우스
9011,집합시설,전시장,기타 전시장
11168,집합시설,전시장,박물관
14669,집합시설,전시장,기념관
24090,집합시설,전시장,미술관
25204,집합시설,전시장,산업전시장
73507,집합시설,전시장,박람회장
124360,집합시설,전시장,과학관

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
9648,문화재시설,문화재,국가지정문화재
11686,문화재시설,문화재,시도지정문화재
20504,문화재시설,문화재,기타 문화재

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
10293,판매/업무시설,청소년시설,생활권수련시설(청소년수련관/ 청소년문화의집 등)
34627,판매/업무시설,청소년시설,기타 청소년시설
53716,판매/업무시설,청소년시설,자연권수련시설(청소년수련원/ 청소년야영장 등)

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
11375,위험물/가스제조소,가스제조소등,기타 가스제조소
35406,위험물/가스제조소,가스제조소등,고압가스저장시설
38191,위험물/가스제조소,가스제조소등,가스공급시설
72793,위험물/가스제조소,가스제조소등,고압가스제조시설
101692,위험물/가스제조소,가스제조소등,액화석유가스저장시설

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
11505,운수자동차시설,항공시설,기타 항공시설
68755,운수자동차시설,항공시설,여행객이용시설(공항)
149896,운수자동차시설,항공시설,통신시설(관제소/ 송신소 등)
168762,운수자동차시설,항공시설,이착륙시설(활주로/ 유도등 등)

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
19203,자동차/철도차량,군용차량,군용차량
51971,자동차/철도차량,군용차량,기타 군용차량

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
21709,자동차/철도차량,철도차량,전동차
29530,자동차/철도차량,철도차량,기관차
107744,자동차/철도차량,철도차량,기타(철도차량)

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
25815,운수자동차시설,항만시설,조선소
37712,운수자동차시설,항만시설,기타 항만시설
139026,운수자동차시설,항만시설,여객이용시설

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
30932,산업시설,지중시설,터널
41595,산업시설,지중시설,기타 지중시설
54913,산업시설,지중시설,공동구
197015,산업시설,지중시설,전력구/ 통신구

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
35269,판매/업무시설,교정시설,교도소/ 구치소
42521,판매/업무시설,교정시설,기타 교정시설

,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
75061,선박/항공기,항공기,비행기
141441,선박/항공기,항공기,경비행기
158731,선박/항공기,항공기,기타 항공기
193386,선박/항공기,항공기,회전익항공기(헬리콥터)

## 4. ignition category ~ location

In [ ]:
# ignition category 데이터프레임
ignition_location_df = fire_fighting_df[['fire_firefighting.ignition_factor_category_1', 'fire_firefighting.ignition_factor_category_2']]

In [71]:
fire_fighting_df.to_pickle('fire_firefighting_datetime.pkl')

In [72]:
fire_fighting_df.columns

Index(['Unnamed: 0', 'fire_firefighting.num', 'fire_firefighting.year',
       'fire_firefighting.tm', 'fire_firefighting.district_1',
       'fire_firefighting.district_2', 'fire_firefighting.fire_type_1',
       'fire_firefighting.fire_type_2',
       'fire_firefighting.ignition_factor_category_1',
       'fire_firefighting.ignition_factor_category_2',
       'fire_firefighting.casualties', 'fire_firefighting.dead',
       'fire_firefighting.injury', 'fire_firefighting.property_damage',
       'fire_firefighting.location_category_1',
       'fire_firefighting.location_category_2',
       'fire_firefighting.location_category_3', 'fire_date', 'month',
       'fire_time'],
      dtype='object')

# 전처리

## 1. 기상데이터 + 화재데이터 (일자별)

In [74]:
fire_fighting_df.head()

,Unnamed: 0,fire_firefighting.num,fire_firefighting.year,fire_firefighting.tm,fire_firefighting.district_1,fire_firefighting.district_2,fire_firefighting.fire_type_1,fire_firefighting.fire_type_2,fire_firefighting.ignition_factor_category_1,fire_firefighting.ignition_factor_category_2,fire_firefighting.casualties,fire_firefighting.dead,fire_firefighting.injury,fire_firefighting.property_damage,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3,fire_date,month,fire_time
0,1,1,2018,2018-01-01 00:03:00,경기도,고양시일산동구,건축,구조물,전기적 요인,미확인단락,1,0,1,24099,주거,단독주택,상가주택(주택부분에서 화재가 발생한 경우에만 해당),2018-01-01,1,00:03:00
1,2,2,2018,2018-01-01 00:12:00,전북특별자치도,완주군,건축,구조물,부주의,가연물 근접방치,0,0,0,2758,주거,단독주택,단독주택,2018-01-01,1,00:12:00
2,3,3,2018,2018-01-01 00:16:00,경기도,남양주시,임야,NaN,부주의,담배꽁초,0,0,0,28,임야,산불,공유림,2018-01-01,1,00:16:00
3,4,4,2018,2018-01-01 00:28:00,충청남도,보령시,건축,구조물,기계적 요인,과열/ 과부하,0,0,0,1942,주거,단독주택,단독주택,2018-01-01,1,00:28:00
4,5,5,2018,2018-01-01 00:38:00,전라남도,순천시,건축,구조물,부주의,가연물 근접방치,0,0,0,1401,주거,단독주택,단독주택,2018-01-01,1,00:38:00

In [81]:
# 필요없는 컬럼 제거
# weather_df.drop('Unnamed: 0', axis=1, inplace=True)
# datetime 객체 변환
weather_df['fire_weather.tm'] = weather_df['fire_weather.tm'].apply(lambda x: pd.to_datetime(x))
weather_df.head()

,fire_weather.tm,fire_weather.district_1,fire_weather.district_2,fire_weather.stn,fire_weather.ta_max,fire_weather.ta_min,fire_weather.ta_max_min,fire_weather.rn_day,fire_weather.ws_max,fire_weather.ws_ins_max,fire_weather.ws_mean,fire_weather.ws_min,fire_weather.hm_max,fire_weather.hm_mean,fire_weather.hm_min
0,2018-01-01,서울특별시,종로구,108,3.8,-5.1,8.9,0.0,3.8,7.0,1.5,0.5,55.6,39.3,20.4
1,2018-01-02,서울특별시,종로구,108,1.8,-4.3,6.1,0.0,4.9,8.5,1.8,0.2,70.6,43.6,20.1
2,2018-01-03,서울특별시,종로구,108,-0.4,-7.1,6.7,0.0,3.5,6.6,2.1,0.8,54.0,41.1,29.3
3,2018-01-04,서울특별시,종로구,108,-0.7,-8.7,8.0,0.0,3.5,5.8,1.4,0.5,56.7,44.1,31.3
4,2018-01-05,서울특별시,종로구,108,1.6,-5.6,7.2,0.0,3.6,8.0,1.7,0.6,56.0,48.5,33.5

In [77]:
# 필요 없는 컬럼 제거
fire_df = fire_fighting_df[['fire_firefighting.num', 'fire_firefighting.tm','fire_date','fire_time', 'fire_firefighting.district_1', 'fire_firefighting.district_2', 'fire_firefighting.fire_type_1', 'fire_firefighting.fire_type_2', 'fire_firefighting.ignition_factor_category_1', 'fire_firefighting.ignition_factor_category_2', 'fire_firefighting.casualties', 'fire_firefighting.dead', 'fire_firefighting.injury', 'fire_firefighting.property_damage', 'fire_firefighting.location_category_1', 'fire_firefighting.location_category_2', 'fire_firefighting.location_category_3']]
fire_df

,fire_firefighting.num,fire_firefighting.tm,fire_date,fire_time,fire_firefighting.district_1,fire_firefighting.district_2,fire_firefighting.fire_type_1,fire_firefighting.fire_type_2,fire_firefighting.ignition_factor_category_1,fire_firefighting.ignition_factor_category_2,fire_firefighting.casualties,fire_firefighting.dead,fire_firefighting.injury,fire_firefighting.property_damage,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
0,1,2018-01-01 00:03:00,2018-01-01,00:03:00,경기도,고양시일산동구,건축,구조물,전기적 요인,미확인단락,1,0,1,24099,주거,단독주택,상가주택(주택부분에서 화재가 발생한 경우에만 해당)
1,2,2018-01-01 00:12:00,2018-01-01,00:12:00,전북특별자치도,완주군,건축,구조물,부주의,가연물 근접방치,0,0,0,2758,주거,단독주택,단독주택
2,3,2018-01-01 00:16:00,2018-01-01,00:16:00,경기도,남양주시,임야,NaN,부주의,담배꽁초,0,0,0,28,임야,산불,공유림
3,4,2018-01-01 00:28:00,2018-01-01,00:28:00,충청남도,보령시,건축,구조물,기계적 요인,과열/ 과부하,0,0,0,1942,주거,단독주택,단독주택
4,5,2018-01-01 00:38:00,2018-01-01,00:38:00,전라남도,순천시,건축,구조물,부주의,가연물 근접방치,0,0,0,1401,주거,단독주택,단독주택
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236332,38853,2023-12-31 23:00:00,2023-12-31,23:00:00,경상남도,양산시,건축,구조물,제품결함,제조상결함,0,0,0,99,판매/업무시설,일반업무,오피스텔
236333,38854,2023-12-31 23:05:00,2023-12-31,23:05:00,부산광역시,북구,건축,구조물,부주의,담배꽁초,0,0,0,30,주거,단독주택,단독주택
236334,38855,2023-12-31 23:35:00,2023-12-31,23:35:00,충청북도,영동군,건축,구조물,미상,미상,0,0,0,13495,주거,기타주택,기타 주택
236335,38856,2023-12-31 23:48:00,2023-12-31,23:48:00,서울특별시,성북구,건축,구조물,부주의,음식물 조리중,0,0,0,12,주거,공동주택,연립주택
236336,38857,2023-12-31 23:50:00,2023-12-31,23:50:00,경기도,김포시,건축,구조물,전기적 요인,절연열화에 의한 단락,0,0,0,3509,산업시설,공장시설,금속기계 및 기구공업

In [86]:
# fire_df 컬럼명 변경
fire_df.columns = ['fire_firefighting.num', 'fire_weather.tm', 'fire_date',
       'fire_time', 'fire_firefighting.district_1',
       'fire_firefighting.district_2', 'fire_firefighting.fire_type_1',
       'fire_firefighting.fire_type_2',
       'fire_firefighting.ignition_factor_category_1',
       'fire_firefighting.ignition_factor_category_2',
       'fire_firefighting.casualties', 'fire_firefighting.dead',
       'fire_firefighting.injury', 'fire_firefighting.property_damage',
       'fire_firefighting.location_category_1',
       'fire_firefighting.location_category_2',
       'fire_firefighting.location_category_3']
fire_df

,fire_firefighting.num,fire_weather.tm,fire_date,fire_time,fire_firefighting.district_1,fire_firefighting.district_2,fire_firefighting.fire_type_1,fire_firefighting.fire_type_2,fire_firefighting.ignition_factor_category_1,fire_firefighting.ignition_factor_category_2,fire_firefighting.casualties,fire_firefighting.dead,fire_firefighting.injury,fire_firefighting.property_damage,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
0,1,2018-01-01 00:03:00,2018-01-01,00:03:00,경기도,고양시일산동구,건축,구조물,전기적 요인,미확인단락,1,0,1,24099,주거,단독주택,상가주택(주택부분에서 화재가 발생한 경우에만 해당)
1,2,2018-01-01 00:12:00,2018-01-01,00:12:00,전북특별자치도,완주군,건축,구조물,부주의,가연물 근접방치,0,0,0,2758,주거,단독주택,단독주택
2,3,2018-01-01 00:16:00,2018-01-01,00:16:00,경기도,남양주시,임야,NaN,부주의,담배꽁초,0,0,0,28,임야,산불,공유림
3,4,2018-01-01 00:28:00,2018-01-01,00:28:00,충청남도,보령시,건축,구조물,기계적 요인,과열/ 과부하,0,0,0,1942,주거,단독주택,단독주택
4,5,2018-01-01 00:38:00,2018-01-01,00:38:00,전라남도,순천시,건축,구조물,부주의,가연물 근접방치,0,0,0,1401,주거,단독주택,단독주택
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236332,38853,2023-12-31 23:00:00,2023-12-31,23:00:00,경상남도,양산시,건축,구조물,제품결함,제조상결함,0,0,0,99,판매/업무시설,일반업무,오피스텔
236333,38854,2023-12-31 23:05:00,2023-12-31,23:05:00,부산광역시,북구,건축,구조물,부주의,담배꽁초,0,0,0,30,주거,단독주택,단독주택
236334,38855,2023-12-31 23:35:00,2023-12-31,23:35:00,충청북도,영동군,건축,구조물,미상,미상,0,0,0,13495,주거,기타주택,기타 주택
236335,38856,2023-12-31 23:48:00,2023-12-31,23:48:00,서울특별시,성북구,건축,구조물,부주의,음식물 조리중,0,0,0,12,주거,공동주택,연립주택
236336,38857,2023-12-31 23:50:00,2023-12-31,23:50:00,경기도,김포시,건축,구조물,전기적 요인,절연열화에 의한 단락,0,0,0,3509,산업시설,공장시설,금속기계 및 기구공업

In [96]:
# 날씨데이터 + 화재데이터 일 기준 결합
fire_weather_df = pd.merge(weather_df, fire_df, left_on=['fire_weather.tm', 'fire_weather.district_1', 'fire_weather.district_2'] 
                           , right_on=['fire_weather.tm', 'fire_firefighting.district_1','fire_firefighting.district_2',], how='left')
fire_weather_df

,fire_weather.tm,fire_weather.district_1,fire_weather.district_2,fire_weather.stn,fire_weather.ta_max,fire_weather.ta_min,fire_weather.ta_max_min,fire_weather.rn_day,fire_weather.ws_max,fire_weather.ws_ins_max,...,fire_firefighting.fire_type_2,fire_firefighting.ignition_factor_category_1,fire_firefighting.ignition_factor_category_2,fire_firefighting.casualties,fire_firefighting.dead,fire_firefighting.injury,fire_firefighting.property_damage,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
0,2018-01-01,서울특별시,종로구,108,3.8,-5.1,8.9,0.0,3.8,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-02,서울특별시,종로구,108,1.8,-4.3,6.1,0.0,4.9,8.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-01-03,서울특별시,종로구,108,-0.4,-7.1,6.7,0.0,3.5,6.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-01-04,서울특별시,종로구,108,-0.7,-8.7,8.0,0.0,3.5,5.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-01-05,서울특별시,종로구,108,1.6,-5.6,7.2,0.0,3.6,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
552574,2023-12-27,강원특별자치도,양양군,670,6.6,-3.0,9.6,0.0,4.1,5.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
552575,2023-12-28,강원특별자치도,양양군,670,7.4,-3.8,11.2,0.0,6.5,10.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
552576,2023-12-29,강원특별자치도,양양군,670,9.3,1.6,7.7,0.0,7.2,10.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
552577,2023-12-30,강원특별자치도,양양군,670,6.0,1.4,4.6,0.5,5.8,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
552578,2023-12-31,강원특별자치도,양양군,670,3.0,0.6,2.4,11.0,5.2,7.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [116]:
# 일자별 화재 건수 count
fire_count_df = fire_weather_df.groupby('fire_weather.tm')[['fire_firefighting.num']].count()
fire_count_df=fire_count_df.reset_index()
fire_count_df['duplicate_counts'] = fire_count_df.groupby('fire_weather.tm')['fire_weather.tm'].transform('size')
fire_count_df.head(50)

   fire_weather.tm  fire_firefighting.num  duplicate_counts
0       2018-01-01                      0                 1
1       2018-01-02                      0                 1
2       2018-01-03                      0                 1
3       2018-01-04                      0                 1
4       2018-01-05                      0                 1
5       2018-01-06                      0                 1
6       2018-01-07                      0                 1
7       2018-01-08                      0                 1
8       2018-01-09                      0                 1
9       2018-01-10                      0                 1
10      2018-01-11                      0                 1
11      2018-01-12                      0                 1
12      2018-01-13                      0                 1
13      2018-01-14                      0                 1
14      2018-01-15                      0                 1
15      2018-01-16                      0                 1
16      2018-01-17                      0                 1
17      2018-01-18                      0                 1
18      2018-01-19                      0                 1
19      2018-01-20                      0                 1
20      2018-01-21                      0                 1
21      2018-01-22                      0                 1
22      2018-01-23                      0                 1
23      2018-01-24                      1                 1
24      2018-01-25                      0                 1
25      2018-01-26                      0                 1
26      2018-01-27                      0                 1
27      2018-01-28                      1                 1
28      2018-01-29                      1                 1
29      2018-01-30                      0                 1
30      2018-01-31                      0                 1
31      2018-02-01                      0                 1
32      2018-02-02                      0                 1
33      2018-02-03                      0                 1
34      2018-02-04                      1                 1
35      2018-02-05                      0                 1
36      2018-02-06                      0                 1
37      2018-02-07                      0                 1
38      2018-02-08                      0                 1
39      2018-02-09                      0                 1
40      2018-02-10                      0                 1
41      2018-02-11                      0                 1
42      2018-02-12                      0                 1
43      2018-02-13                      0                 1
44      2018-02-14                      0                 1
45      2018-02-15                      0                 1
46      2018-02-16                      0                 1
47      2018-02-17                      0                 1
48      2018-02-18                      0                 1
49      2018-02-19                      0                 1

In [101]:
fire_count_df[fire_count_df['fire_firefighting.num']!=0]

                 fire_firefighting.num
fire_weather.tm
2018-01-24                           1
2018-01-28                           1
2018-01-29                           1
2018-02-04                           1
2018-02-27                           1
...                                ...
2023-11-13                           1
2023-11-28                           1
2023-12-13                           1
2023-12-23                           1
2023-12-24                           1

[120 rows x 1 columns]

In [103]:
fire_df[fire_df['fire_date'] == pd.to_datetime('2018-01-18')]

,fire_firefighting.num,fire_weather.tm,fire_date,fire_time,fire_firefighting.district_1,fire_firefighting.district_2,fire_firefighting.fire_type_1,fire_firefighting.fire_type_2,fire_firefighting.ignition_factor_category_1,fire_firefighting.ignition_factor_category_2,fire_firefighting.casualties,fire_firefighting.dead,fire_firefighting.injury,fire_firefighting.property_damage,fire_firefighting.location_category_1,fire_firefighting.location_category_2,fire_firefighting.location_category_3
2017,2018,2018-01-18 00:08:00,2018-01-18,00:08:00,경상남도,김해시,건축,구조물,방화의심,방화의심,0,0,0,641,판매/업무시설,판매시설,상가빌딩
2018,2019,2018-01-18 00:46:00,2018-01-18,00:46:00,부산광역시,북구,건축,구조물,방화,방화,0,0,0,809,주거,단독주택,단독주택
2019,2020,2018-01-18 00:49:00,2018-01-18,00:49:00,서울특별시,영등포구,건축,구조물,전기적 요인,절연열화에 의한 단락,0,0,0,19,생활서비스,음식점,중식
2020,2021,2018-01-18 01:04:00,2018-01-18,01:04:00,서울특별시,성북구,건축,구조물,부주의,빨래삶기,1,0,1,45,의료/복지시설,노유자시설,요양시설
2021,2022,2018-01-18 01:12:00,2018-01-18,01:12:00,서울특별시,서초구,건축,구조물,부주의,담배꽁초,0,0,0,29,주거,단독주택,다가구주택
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2123,2124,2018-01-18 23:24:00,2018-01-18,23:24:00,부산광역시,서구,건축,구조물,전기적 요인,미확인단락,0,0,0,708,주거,공동주택,아파트
2124,2125,2018-01-18 23:37:00,2018-01-18,23:37:00,서울특별시,강서구,건축,구조물,부주의,음식물 조리중,0,0,0,20,주거,공동주택,기타 공동주택
2125,2126,2018-01-18 23:43:00,2018-01-18,23:43:00,부산광역시,부산진구,건축,구조물,부주의,음식물 조리중,0,0,0,31,주거,단독주택,상가주택(주택부분에서 화재가 발생한 경우에만 해당)
2126,2127,2018-01-18 23:50:00,2018-01-18,23:50:00,경상남도,김해시,자동차,철도차량,전기적 요인,절연열화에 의한 단락,0,0,0,4461,자동차/철도차량,자동차,버스
2127,2128,2018-01-18 23:51:00,2018-01-18,23:51:00,경기도,고양시일산동구,건축,구조물,부주의,불씨/불꽃/화원방치,0,0,0,11140,생활서비스,음식점,한식

## 열끼리 unique 값 확인

In [11]:
type_list = fire_fighting_df['fire_firefighting.fire_type_1'].unique()
for type in type_list:
    print(f'fire type: {type}')
    print('location')
    print(fire_fighting_df[fire_fighting_df['fire_firefighting.fire_type_1'] == type]['fire_firefighting.location_category_1'].unique())
    print()

fire type: 건축
location
['주거' '생활서비스' '기타서비스' '산업시설' '판매/업무시설' '운수자동차시설' '교육시설' '집합시설' '의료/복지시설'
 '문화재시설']

fire type: 임야
location
['임야']

fire type: 기타(쓰레기 화재등)
location
['기타']

fire type: 자동차
location
['자동차/철도차량']

fire type: 위험물
location
['위험물/가스제조소']

fire type: 선박
location
['선박/항공기']

In [10]:
ignition_list = fire_fighting_df['fire_firefighting.ignition_factor_category_1'].unique()
for ignition in ignition_list:
    print(f'ignition factor: {ignition}')
    print('fire_type:')
    print(fire_fighting_df[fire_fighting_df['fire_firefighting.ignition_factor_category_1']==ignition]['fire_firefighting.fire_type_1'].unique())
    print()

ignition factor: 전기적 요인
fire_type:
['건축' '기타(쓰레기 화재등)' '자동차' '임야' '선박' '위험물']

ignition factor: 부주의
fire_type:
['건축' '임야' '기타(쓰레기 화재등)' '자동차' '위험물' '선박']

ignition factor: 기계적 요인
fire_type:
['건축' '자동차' '기타(쓰레기 화재등)' '임야' '선박' '위험물']

ignition factor: 미상
fire_type:
['임야' '건축' '자동차' '위험물' '기타(쓰레기 화재등)' '선박']

ignition factor: 방화의심
fire_type:
['건축' '기타(쓰레기 화재등)' '자동차' '임야' '선박']

ignition factor: 기타
fire_type:
['건축' '임야' '자동차' '기타(쓰레기 화재등)' '위험물' '선박']

ignition factor: 방화
fire_type:
['건축' '임야' '자동차' '기타(쓰레기 화재등)' '위험물' '선박']

ignition factor: 교통사고
fire_type:
['자동차' '기타(쓰레기 화재등)' '위험물' '건축' '임야' '선박']

ignition factor: 가스누출(폭발)
fire_type:
['건축' '기타(쓰레기 화재등)' '자동차' '선박' '위험물' '임야']

ignition factor: 화학적 요인
fire_type:
['건축' '기타(쓰레기 화재등)' '자동차' '위험물' '임야' '선박']

ignition factor: 자연적인 요인
fire_type:
['기타(쓰레기 화재등)' '건축' '임야' '자동차' '선박' '위험물']

ignition factor: 제품결함
fire_type:
['건축' '자동차' '기타(쓰레기 화재등)']

In [17]:
# 화재 유형
unique_combinations = fire_fighting_df[['fire_firefighting.fire_type_1', 'fire_firefighting.ignition_factor_category_1', 'fire_firefighting.location_category_1']].drop_duplicates()
for i in range(163):
    display(unique_combinations.iloc[i, :])
    print()

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    전기적 요인
fire_firefighting.location_category_1               주거
Name: 0, dtype: object

fire_firefighting.fire_type_1                    건축
fire_firefighting.ignition_factor_category_1    부주의
fire_firefighting.location_category_1            주거
Name: 1, dtype: object

fire_firefighting.fire_type_1                    임야
fire_firefighting.ignition_factor_category_1    부주의
fire_firefighting.location_category_1            임야
Name: 2, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    기계적 요인
fire_firefighting.location_category_1               주거
Name: 3, dtype: object

fire_firefighting.fire_type_1                   기타(쓰레기 화재등)
fire_firefighting.ignition_factor_category_1         전기적 요인
fire_firefighting.location_category_1                    기타
Name: 7, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1      부주의
fire_firefighting.location_category_1           생활서비스
Name: 8, dtype: object

fire_firefighting.fire_type_1                   기타(쓰레기 화재등)
fire_firefighting.ignition_factor_category_1            부주의
fire_firefighting.location_category_1                    기타
Name: 12, dtype: object

fire_firefighting.fire_type_1                   임야
fire_firefighting.ignition_factor_category_1    미상
fire_firefighting.location_category_1           임야
Name: 13, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1       미상
fire_firefighting.location_category_1           기타서비스
Name: 14, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    전기적 요인
fire_firefighting.location_category_1             산업시설
Name: 16, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1       미상
fire_firefighting.location_category_1           생활서비스
Name: 19, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1    방화의심
fire_firefighting.location_category_1             주거
Name: 22, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1       방화의심
fire_firefighting.location_category_1           판매/업무시설
Name: 24, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1      미상
fire_firefighting.location_category_1           산업시설
Name: 28, dtype: object

fire_firefighting.fire_type_1                        자동차
fire_firefighting.ignition_factor_category_1      기계적 요인
fire_firefighting.location_category_1           자동차/철도차량
Name: 30, dtype: object

fire_firefighting.fire_type_1                        자동차
fire_firefighting.ignition_factor_category_1      전기적 요인
fire_firefighting.location_category_1           자동차/철도차량
Name: 31, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1         미상
fire_firefighting.location_category_1           판매/업무시설
Name: 32, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    전기적 요인
fire_firefighting.location_category_1            생활서비스
Name: 34, dtype: object

fire_firefighting.fire_type_1                   건축
fire_firefighting.ignition_factor_category_1    기타
fire_firefighting.location_category_1           주거
Name: 36, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    전기적 요인
fire_firefighting.location_category_1            기타서비스
Name: 38, dtype: object

fire_firefighting.fire_type_1                   건축
fire_firefighting.ignition_factor_category_1    방화
fire_firefighting.location_category_1           주거
Name: 40, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1     전기적 요인
fire_firefighting.location_category_1           판매/업무시설
Name: 44, dtype: object

fire_firefighting.fire_type_1                        자동차
fire_firefighting.ignition_factor_category_1         부주의
fire_firefighting.location_category_1           자동차/철도차량
Name: 58, dtype: object

fire_firefighting.fire_type_1                   건축
fire_firefighting.ignition_factor_category_1    미상
fire_firefighting.location_category_1           주거
Name: 59, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1     부주의
fire_firefighting.location_category_1           산업시설
Name: 63, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1     전기적 요인
fire_firefighting.location_category_1           운수자동차시설
Name: 83, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    전기적 요인
fire_firefighting.location_category_1             교육시설
Name: 90, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    기계적 요인
fire_firefighting.location_category_1             산업시설
Name: 92, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1     부주의
fire_firefighting.location_category_1           교육시설
Name: 93, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1      기타
fire_firefighting.location_category_1           산업시설
Name: 96, dtype: object

fire_firefighting.fire_type_1                        자동차
fire_firefighting.ignition_factor_category_1          미상
fire_firefighting.location_category_1           자동차/철도차량
Name: 100, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1        부주의
fire_firefighting.location_category_1           판매/업무시설
Name: 101, dtype: object

fire_firefighting.fire_type_1                        자동차
fire_firefighting.ignition_factor_category_1        교통사고
fire_firefighting.location_category_1           자동차/철도차량
Name: 113, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1     기계적 요인
fire_firefighting.location_category_1           판매/업무시설
Name: 124, dtype: object

fire_firefighting.fire_type_1                   기타(쓰레기 화재등)
fire_firefighting.ignition_factor_category_1         기계적 요인
fire_firefighting.location_category_1                    기타
Name: 125, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1      미상
fire_firefighting.location_category_1           집합시설
Name: 127, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    기계적 요인
fire_firefighting.location_category_1            생활서비스
Name: 144, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1      부주의
fire_firefighting.location_category_1           기타서비스
Name: 145, dtype: object

fire_firefighting.fire_type_1                         위험물
fire_firefighting.ignition_factor_category_1           미상
fire_firefighting.location_category_1           위험물/가스제조소
Name: 147, dtype: object

fire_firefighting.fire_type_1                         건축
fire_firefighting.ignition_factor_category_1    가스누출(폭발)
fire_firefighting.location_category_1              생활서비스
Name: 182, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1     기계적 요인
fire_firefighting.location_category_1           운수자동차시설
Name: 184, dtype: object

fire_firefighting.fire_type_1                   기타(쓰레기 화재등)
fire_firefighting.ignition_factor_category_1           방화의심
fire_firefighting.location_category_1                    기타
Name: 192, dtype: object

fire_firefighting.fire_type_1                   임야
fire_firefighting.ignition_factor_category_1    방화
fire_firefighting.location_category_1           임야
Name: 212, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1     부주의
fire_firefighting.location_category_1           집합시설
Name: 215, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    화학적 요인
fire_firefighting.location_category_1               주거
Name: 224, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1         방화
fire_firefighting.location_category_1           판매/업무시설
Name: 237, dtype: object

fire_firefighting.fire_type_1                       임야
fire_firefighting.ignition_factor_category_1    전기적 요인
fire_firefighting.location_category_1               임야
Name: 243, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    화학적 요인
fire_firefighting.location_category_1            생활서비스
Name: 249, dtype: object

fire_firefighting.fire_type_1                   기타(쓰레기 화재등)
fire_firefighting.ignition_factor_category_1             미상
fire_firefighting.location_category_1                    기타
Name: 253, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    기계적 요인
fire_firefighting.location_category_1            기타서비스
Name: 287, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1     기계적 요인
fire_firefighting.location_category_1           의료/복지시설
Name: 297, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    전기적 요인
fire_firefighting.location_category_1             집합시설
Name: 330, dtype: object

fire_firefighting.fire_type_1                   기타(쓰레기 화재등)
fire_firefighting.ignition_factor_category_1         화학적 요인
fire_firefighting.location_category_1                    기타
Name: 380, dtype: object

fire_firefighting.fire_type_1                   임야
fire_firefighting.ignition_factor_category_1    기타
fire_firefighting.location_category_1           임야
Name: 406, dtype: object

fire_firefighting.fire_type_1                        자동차
fire_firefighting.ignition_factor_category_1          기타
fire_firefighting.location_category_1           자동차/철도차량
Name: 418, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    화학적 요인
fire_firefighting.location_category_1             산업시설
Name: 563, dtype: object

fire_firefighting.fire_type_1                         건축
fire_firefighting.ignition_factor_category_1    가스누출(폭발)
fire_firefighting.location_category_1              기타서비스
Name: 581, dtype: object

fire_firefighting.fire_type_1                   기타(쓰레기 화재등)
fire_firefighting.ignition_factor_category_1             기타
fire_firefighting.location_category_1                    기타
Name: 583, dtype: object

fire_firefighting.fire_type_1                       임야
fire_firefighting.ignition_factor_category_1    기계적 요인
fire_firefighting.location_category_1               임야
Name: 620, dtype: object

fire_firefighting.fire_type_1                   기타(쓰레기 화재등)
fire_firefighting.ignition_factor_category_1       가스누출(폭발)
fire_firefighting.location_category_1                    기타
Name: 694, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1     전기적 요인
fire_firefighting.location_category_1           의료/복지시설
Name: 705, dtype: object

fire_firefighting.fire_type_1                         위험물
fire_firefighting.ignition_factor_category_1          부주의
fire_firefighting.location_category_1           위험물/가스제조소
Name: 753, dtype: object

fire_firefighting.fire_type_1                         건축
fire_firefighting.ignition_factor_category_1    가스누출(폭발)
fire_firefighting.location_category_1                 주거
Name: 766, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1         방화
fire_firefighting.location_category_1           의료/복지시설
Name: 803, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1        부주의
fire_firefighting.location_category_1           운수자동차시설
Name: 863, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1     화학적 요인
fire_firefighting.location_category_1           판매/업무시설
Name: 945, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1      미상
fire_firefighting.location_category_1           교육시설
Name: 962, dtype: object

fire_firefighting.fire_type_1                       선박
fire_firefighting.ignition_factor_category_1    전기적 요인
fire_firefighting.location_category_1           선박/항공기
Name: 980, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1        부주의
fire_firefighting.location_category_1           의료/복지시설
Name: 991, dtype: object

fire_firefighting.fire_type_1                   기타(쓰레기 화재등)
fire_firefighting.ignition_factor_category_1        자연적인 요인
fire_firefighting.location_category_1                    기타
Name: 1012, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1    방화의심
fire_firefighting.location_category_1           산업시설
Name: 1032, dtype: object

fire_firefighting.fire_type_1                        자동차
fire_firefighting.ignition_factor_category_1    가스누출(폭발)
fire_firefighting.location_category_1           자동차/철도차량
Name: 1063, dtype: object

fire_firefighting.fire_type_1                   기타(쓰레기 화재등)
fire_firefighting.ignition_factor_category_1           교통사고
fire_firefighting.location_category_1                    기타
Name: 1069, dtype: object

fire_firefighting.fire_type_1                       선박
fire_firefighting.ignition_factor_category_1       부주의
fire_firefighting.location_category_1           선박/항공기
Name: 1078, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1         기타
fire_firefighting.location_category_1           판매/업무시설
Name: 1116, dtype: object

fire_firefighting.fire_type_1                        자동차
fire_firefighting.ignition_factor_category_1          방화
fire_firefighting.location_category_1           자동차/철도차량
Name: 1149, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    기계적 요인
fire_firefighting.location_category_1             집합시설
Name: 1160, dtype: object

fire_firefighting.fire_type_1                       선박
fire_firefighting.ignition_factor_category_1        미상
fire_firefighting.location_category_1           선박/항공기
Name: 1185, dtype: object

fire_firefighting.fire_type_1                        자동차
fire_firefighting.ignition_factor_category_1        방화의심
fire_firefighting.location_category_1           자동차/철도차량
Name: 1209, dtype: object

fire_firefighting.fire_type_1                         건축
fire_firefighting.ignition_factor_category_1    가스누출(폭발)
fire_firefighting.location_category_1               산업시설
Name: 1321, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1       방화
fire_firefighting.location_category_1           생활서비스
Name: 1563, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1       기타
fire_firefighting.location_category_1           기타서비스
Name: 1567, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1    자연적인 요인
fire_firefighting.location_category_1             생활서비스
Name: 1618, dtype: object

fire_firefighting.fire_type_1                     임야
fire_firefighting.ignition_factor_category_1    방화의심
fire_firefighting.location_category_1             임야
Name: 1699, dtype: object

fire_firefighting.fire_type_1                        자동차
fire_firefighting.ignition_factor_category_1      화학적 요인
fire_firefighting.location_category_1           자동차/철도차량
Name: 1711, dtype: object

fire_firefighting.fire_type_1                         건축
fire_firefighting.ignition_factor_category_1    가스누출(폭발)
fire_firefighting.location_category_1            판매/업무시설
Name: 1918, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1         미상
fire_firefighting.location_category_1           운수자동차시설
Name: 1957, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1     방화의심
fire_firefighting.location_category_1           생활서비스
Name: 2153, dtype: object

fire_firefighting.fire_type_1                         위험물
fire_firefighting.ignition_factor_category_1         교통사고
fire_firefighting.location_category_1           위험물/가스제조소
Name: 2235, dtype: object

fire_firefighting.fire_type_1                   기타(쓰레기 화재등)
fire_firefighting.ignition_factor_category_1             방화
fire_firefighting.location_category_1                    기타
Name: 2415, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1    자연적인 요인
fire_firefighting.location_category_1           판매/업무시설
Name: 2553, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1       기타
fire_firefighting.location_category_1           생활서비스
Name: 2599, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1         미상
fire_firefighting.location_category_1           의료/복지시설
Name: 2707, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1      기타
fire_firefighting.location_category_1           집합시설
Name: 3602, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    기계적 요인
fire_firefighting.location_category_1             교육시설
Name: 3659, dtype: object

fire_firefighting.fire_type_1                         건축
fire_firefighting.ignition_factor_category_1    가스누출(폭발)
fire_firefighting.location_category_1            운수자동차시설
Name: 3757, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1    자연적인 요인
fire_firefighting.location_category_1                주거
Name: 4127, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1       방화의심
fire_firefighting.location_category_1           의료/복지시설
Name: 4155, dtype: object

fire_firefighting.fire_type_1                       선박
fire_firefighting.ignition_factor_category_1    기계적 요인
fire_firefighting.location_category_1           선박/항공기
Name: 4805, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1      방화
fire_firefighting.location_category_1           산업시설
Name: 5094, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1     방화의심
fire_firefighting.location_category_1           기타서비스
Name: 5418, dtype: object

fire_firefighting.fire_type_1                         위험물
fire_firefighting.ignition_factor_category_1       화학적 요인
fire_firefighting.location_category_1           위험물/가스제조소
Name: 6094, dtype: object

fire_firefighting.fire_type_1                       임야
fire_firefighting.ignition_factor_category_1    화학적 요인
fire_firefighting.location_category_1               임야
Name: 7255, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1         기타
fire_firefighting.location_category_1           의료/복지시설
Name: 7646, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1    자연적인 요인
fire_firefighting.location_category_1              산업시설
Name: 7879, dtype: object

fire_firefighting.fire_type_1                         건축
fire_firefighting.ignition_factor_category_1    가스누출(폭발)
fire_firefighting.location_category_1               집합시설
Name: 7916, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1       방화
fire_firefighting.location_category_1           기타서비스
Name: 8228, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1    방화의심
fire_firefighting.location_category_1           집합시설
Name: 8246, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1       방화
fire_firefighting.location_category_1           문화재시설
Name: 9648, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    화학적 요인
fire_firefighting.location_category_1             교육시설
Name: 10534, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1         기타
fire_firefighting.location_category_1           운수자동차시설
Name: 10919, dtype: object

fire_firefighting.fire_type_1                       선박
fire_firefighting.ignition_factor_category_1    화학적 요인
fire_firefighting.location_category_1           선박/항공기
Name: 11300, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    전기적 요인
fire_firefighting.location_category_1            문화재시설
Name: 11686, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1     화학적 요인
fire_firefighting.location_category_1           의료/복지시설
Name: 12497, dtype: object

fire_firefighting.fire_type_1                         건축
fire_firefighting.ignition_factor_category_1    가스누출(폭발)
fire_firefighting.location_category_1            의료/복지시설
Name: 13367, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1    자연적인 요인
fire_firefighting.location_category_1           의료/복지시설
Name: 13543, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1      방화
fire_firefighting.location_category_1           집합시설
Name: 13904, dtype: object

fire_firefighting.fire_type_1                         위험물
fire_firefighting.ignition_factor_category_1       기계적 요인
fire_firefighting.location_category_1           위험물/가스제조소
Name: 14391, dtype: object

fire_firefighting.fire_type_1                        임야
fire_firefighting.ignition_factor_category_1    자연적인 요인
fire_firefighting.location_category_1                임야
Name: 14592, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1    방화의심
fire_firefighting.location_category_1           교육시설
Name: 15688, dtype: object

fire_firefighting.fire_type_1                         선박
fire_firefighting.ignition_factor_category_1    가스누출(폭발)
fire_firefighting.location_category_1             선박/항공기
Name: 17638, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1    자연적인 요인
fire_firefighting.location_category_1             기타서비스
Name: 17827, dtype: object

fire_firefighting.fire_type_1                        자동차
fire_firefighting.ignition_factor_category_1     자연적인 요인
fire_firefighting.location_category_1           자동차/철도차량
Name: 17843, dtype: object

fire_firefighting.fire_type_1                         위험물
fire_firefighting.ignition_factor_category_1     가스누출(폭발)
fire_firefighting.location_category_1           위험물/가스제조소
Name: 18259, dtype: object

fire_firefighting.fire_type_1                         위험물
fire_firefighting.ignition_factor_category_1           기타
fire_firefighting.location_category_1           위험물/가스제조소
Name: 19118, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1         방화
fire_firefighting.location_category_1           운수자동차시설
Name: 19906, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    화학적 요인
fire_firefighting.location_category_1            기타서비스
Name: 22174, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1       방화의심
fire_firefighting.location_category_1           운수자동차시설
Name: 23158, dtype: object

fire_firefighting.fire_type_1                         건축
fire_firefighting.ignition_factor_category_1    가스누출(폭발)
fire_firefighting.location_category_1               교육시설
Name: 24248, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1     화학적 요인
fire_firefighting.location_category_1           운수자동차시설
Name: 29464, dtype: object

fire_firefighting.fire_type_1                       건축
fire_firefighting.ignition_factor_category_1    화학적 요인
fire_firefighting.location_category_1             집합시설
Name: 32709, dtype: object

fire_firefighting.fire_type_1                       선박
fire_firefighting.ignition_factor_category_1        기타
fire_firefighting.location_category_1           선박/항공기
Name: 33835, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1      기타
fire_firefighting.location_category_1           교육시설
Name: 39828, dtype: object

fire_firefighting.fire_type_1                         위험물
fire_firefighting.ignition_factor_category_1       전기적 요인
fire_firefighting.location_category_1           위험물/가스제조소
Name: 40052, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1     교통사고
fire_firefighting.location_category_1           생활서비스
Name: 40227, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1    자연적인 요인
fire_firefighting.location_category_1              집합시설
Name: 52384, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1    자연적인 요인
fire_firefighting.location_category_1           운수자동차시설
Name: 63231, dtype: object

fire_firefighting.fire_type_1                         위험물
fire_firefighting.ignition_factor_category_1           방화
fire_firefighting.location_category_1           위험물/가스제조소
Name: 70407, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1      방화
fire_firefighting.location_category_1           교육시설
Name: 76255, dtype: object

fire_firefighting.fire_type_1                       선박
fire_firefighting.ignition_factor_category_1      방화의심
fire_firefighting.location_category_1           선박/항공기
Name: 77999, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1      부주의
fire_firefighting.location_category_1           문화재시설
Name: 78544, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1    제품결함
fire_firefighting.location_category_1             주거
Name: 84616, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1    자연적인 요인
fire_firefighting.location_category_1              교육시설
Name: 97426, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1    제품결함
fire_firefighting.location_category_1           산업시설
Name: 99097, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1       제품결함
fire_firefighting.location_category_1           판매/업무시설
Name: 99143, dtype: object

fire_firefighting.fire_type_1                        자동차
fire_firefighting.ignition_factor_category_1        제품결함
fire_firefighting.location_category_1           자동차/철도차량
Name: 99949, dtype: object

fire_firefighting.fire_type_1                   기타(쓰레기 화재등)
fire_firefighting.ignition_factor_category_1           제품결함
fire_firefighting.location_category_1                    기타
Name: 103824, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1     제품결함
fire_firefighting.location_category_1           생활서비스
Name: 104323, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1    제품결함
fire_firefighting.location_category_1           교육시설
Name: 106667, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1    교통사고
fire_firefighting.location_category_1           산업시설
Name: 108199, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1       제품결함
fire_firefighting.location_category_1           의료/복지시설
Name: 119685, dtype: object

fire_firefighting.fire_type_1                     건축
fire_firefighting.ignition_factor_category_1    제품결함
fire_firefighting.location_category_1           집합시설
Name: 121269, dtype: object

fire_firefighting.fire_type_1                       선박
fire_firefighting.ignition_factor_category_1        방화
fire_firefighting.location_category_1           선박/항공기
Name: 132243, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1       미상
fire_firefighting.location_category_1           문화재시설
Name: 134050, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1     제품결함
fire_firefighting.location_category_1           기타서비스
Name: 136224, dtype: object

fire_firefighting.fire_type_1                      건축
fire_firefighting.ignition_factor_category_1     교통사고
fire_firefighting.location_category_1           기타서비스
Name: 137009, dtype: object

fire_firefighting.fire_type_1                        선박
fire_firefighting.ignition_factor_category_1    자연적인 요인
fire_firefighting.location_category_1            선박/항공기
Name: 140821, dtype: object

fire_firefighting.fire_type_1                         위험물
fire_firefighting.ignition_factor_category_1      자연적인 요인
fire_firefighting.location_category_1           위험물/가스제조소
Name: 141015, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1       제품결함
fire_firefighting.location_category_1           운수자동차시설
Name: 158752, dtype: object

fire_firefighting.fire_type_1                     임야
fire_firefighting.ignition_factor_category_1    교통사고
fire_firefighting.location_category_1             임야
Name: 170199, dtype: object

fire_firefighting.fire_type_1                       선박
fire_firefighting.ignition_factor_category_1      교통사고
fire_firefighting.location_category_1           선박/항공기
Name: 173781, dtype: object

fire_firefighting.fire_type_1                         임야
fire_firefighting.ignition_factor_category_1    가스누출(폭발)
fire_firefighting.location_category_1                 임야
Name: 209861, dtype: object

fire_firefighting.fire_type_1                        건축
fire_firefighting.ignition_factor_category_1       교통사고
fire_firefighting.location_category_1           운수자동차시설
Name: 214182, dtype: object